In [1]:
import pandas as pd
from typing import List, Tuple, Dict, Optional
import numpy as np
from math import radians,cos,sin,asin,sqrt
import matplotlib.pyplot as plt
import seaborn as sns
import os
import scipy.stats as stats
from sklearn.mixture import GaussianMixture
from scipy.optimize import minimize

from shapely.geometry import Point, Polygon, MultiPolygon, MultiPoint
from shapely import wkt
from scipy.spatial import ConvexHull

import geopandas as gpd
import rasterio
from rasterio.mask import mask

from pathlib import Path

# Visualization

## Figure 1: Null Model
For each slice, produce three side-by-side plots:
* Concurrent duration histogram (sim vs obs)
* Event frequency boxplots for tiger-leading (difference > 0)
* Event frequency boxplots for leopard-leading (difference < 0)

In [2]:
import re
import shutil
from pathlib import Path
from typing import Tuple, Optional

def normalize_mc_padding_inplace(
    base_dir: Path,
    id_pair: Tuple[int,int],
    target_width: int = 3,
    dry_run: bool = False,
) -> None:
    """
    In-place rename of simulated parquet files in base_dir so that 'MC' tokens
    use exactly `target_width` digits (default: 3 → MC001, MC051, MC900).
    Observed files (with 'observed_time') are ignored.
    """
    id1, id2 = id_pair
    patterns = [
        f"{id1}_{id2}_slice*_events_*_MC*.parquet",
        f"{id1}_{id2}_slice*_pairs_*_MC*.parquet",
    ]
    mc_re = re.compile(r"(MC)(\d+)")
    renamed = skipped = 0

    for pat in patterns:
        files = list(base_dir.rglob(pat))
        for src in files:
            stem = src.stem
            m = mc_re.search(stem)
            if not m:
                skipped += 1
                continue
            try:
                mc_val = int(m.group(2))
            except ValueError:
                skipped += 1
                continue
            new_token = f"MC{str(mc_val).zfill(target_width)}"
            new_stem = mc_re.sub(new_token, stem, count=1)
            if new_stem == stem:
                skipped += 1
                continue
            dst = src.with_name(new_stem + src.suffix)
            if not dry_run:
                src.rename(dst)
            renamed += 1

    print(f"[normalize] {base_dir}: renamed={renamed}, skipped={skipped}")

In [3]:
import re, shutil
from pathlib import Path

def copy_and_renumber_mc_files(
    id_pair: Tuple[int,int],
    base_dir1: Path,
    base_dir2: Path,
    offset: int = 0,          # MC_new = MC_old + offset
    max_mc_dir2: int = 1000,    # only copy MC in [1, max_mc_dir2]
    target_width: int = 3,
    dry_run: bool = False,
) -> None:
    """
    Copy simulated parquet files from base_dir2 into base_dir1, renumbering MC by +offset,
    and forcing MC token to exactly `target_width` digits (default 3).
    Reproduces the relative directory structure under base_dir1.
    """
    id1, id2 = id_pair
    patterns = [
        f"{id1}_{id2}_slice*_events_*_MC*.parquet",
        f"{id1}_{id2}_slice*_pairs_*_MC*.parquet",
    ]
    mc_re = re.compile(r"(MC)(\d+)")

    base_dir1.mkdir(parents=True, exist_ok=True)
    if not base_dir2.exists():
        raise FileNotFoundError(f"base_dir2 not found: {base_dir2}")

    copied = skipped_exist = skipped_range = scanned = 0
    for pat in patterns:
        for src in base_dir2.rglob(pat):
            scanned += 1
            stem = src.stem
            m = mc_re.search(stem)
            if not m:
                continue
            try:
                mc_old = int(m.group(2))
            except ValueError:
                continue
            if not (1 <= mc_old <= max_mc_dir2):
                skipped_range += 1
                continue

            mc_new = mc_old + offset
            new_token = f"MC{str(mc_new).zfill(target_width)}"
            new_stem = mc_re.sub(new_token, stem, count=1)
            dst_rel = src.relative_to(base_dir2).with_name(new_stem + src.suffix)
            dst = base_dir1 / dst_rel
            dst.parent.mkdir(parents=True, exist_ok=True)

            if dst.exists():
                skipped_exist += 1
                continue

            if not dry_run:
                shutil.copy2(src, dst)
            copied += 1

    print(f"[copy+renumber] {base_dir2} → {base_dir1}: scanned={scanned}, copied={copied}, skip_exist={skipped_exist}, skip_out_of_range={skipped_range}")

In [4]:
from typing import Dict, List, Tuple, Optional
from pathlib import Path
import pandas as pd
import numpy as np
import re

def summarize_interaction_results(
    id_pair: Tuple[int,int],
    base_dir: Optional[Path] = None,
    bin_labels: Optional[List[str]] = None,
    summary_folder: str = "summary",
    max_mc: int = 1000,
    write_out: bool = True,
    verbose: bool = True,
) -> Dict[str, pd.DataFrame]:
    """
    Loader for simulated and observed ORTEGA outputs.
    """
    if bin_labels is None or len(bin_labels) == 0:
        raise ValueError("Please provide bin_labels, e.g. ['0-1h','1h-1d','1-2d',...].")

    id1, id2 = id_pair
    if base_dir is None:
        base_dir = Path(f"../../simulated_trajectory/CRW_slice_RT_WIN1000_MC0001_1000/by_slice_{id1}_{id2}_reverse_time")
    base_dir = Path(base_dir)

    batch_label = f"MC0001_{int(max_mc):04d}"

    # ---- helpers ----
    def _parse_slice_from_path(fp: Path) -> int:
        # filename like "..._slice012_..." -> 12
        m = re.search(r"slice0*(\d+)", fp.stem)
        if not m:
            raise ValueError(f"Cannot parse slice from filename: {fp.name}")
        return int(m.group(1))

    def _parse_mc_from_path(fp: Path) -> Optional[int]:
        m = re.search(r"MC0*(\d+)", fp.stem)
        if not m:
            return None
        try:
            return int(m.group(1))
        except ValueError:
            return None

    def _is_safe_file(fp: Path) -> bool:
        s = str(fp)
        bad_tokens = [
            "_uploaded_zip_extract",
            "_archive",
            "_quarantine",
            "visualization_outputs",
            "summary_hpc",
            "summary",
            "DUPLICATE",
        ]
        return not any(tok in s for tok in bad_tokens)

    def _canonical_interaction_dirs() -> List[Path]:
        dirs = []
        for sdir in sorted(base_dir.glob("slice*")):
            if not sdir.is_dir():
                continue
            int_dir = sdir / batch_label / "interactions"
            if int_dir.exists():
                dirs.append(int_dir)
        return dirs

    def _collect_canonical(pattern_fmt: str, labels: List[str]) -> List[Path]:
        files: List[Path] = []
        for int_dir in _canonical_interaction_dirs():
            for lbl in labels:
                pat = pattern_fmt.format(lbl=lbl)
                files.extend(int_dir.glob(pat))
        # Unique + safe + sorted for reproducibility
        files = sorted(set(fp for fp in files if fp.is_file() and _is_safe_file(fp)))
        return files

    def _load_obs_with_slice(fp: Path) -> pd.DataFrame:
        df = pd.read_parquet(fp)
        # keep original convention of this notebook: slice index displayed as 1-based
        df["slice"] = _parse_slice_from_path(fp) + 1
        # enforce time_bin from filename so filenames determine final bins
        for lbl in bin_labels:
            token = f"_{lbl}_observed_time"
            if token in fp.name:
                df["time_bin"] = lbl
                break
        return df

    def _load_sim_with_slice_if_within(fp: Path) -> Optional[pd.DataFrame]:
        mc = _parse_mc_from_path(fp)
        if mc is None or mc < 1 or mc > max_mc:
            return None
        df = pd.read_parquet(fp)
        # keep original convention of this notebook: slice index displayed as 1-based
        df["slice"] = _parse_slice_from_path(fp) + 1
        # enforce MC_round from filename to avoid inconsistent dtype or stale column
        df["MC_round"] = mc
        for lbl in bin_labels:
            token = f"_{lbl}_MC"
            if token in fp.name:
                df["time_bin"] = lbl
                break
        return df

    # ---------- build file lists restricted to final bin_labels ----------
    sim_events_files = _collect_canonical(
        f"{id1}_{id2}_slice*_events_{{lbl}}_MC*.parquet", bin_labels
    )
    sim_pairs_files  = _collect_canonical(
        f"{id1}_{id2}_slice*_pairs_{{lbl}}_MC*.parquet", bin_labels
    )
    obs_events_files = _collect_canonical(
        f"{id1}_{id2}_slice*_events_{{lbl}}_observed_time.parquet", bin_labels
    )
    obs_pairs_files  = _collect_canonical(
        f"{id1}_{id2}_slice*_pairs_{{lbl}}_observed_time.parquet", bin_labels
    )

    # ---------- load ----------
    dfs: Dict[str, pd.DataFrame] = {}

    parts = []
    for fp in sim_events_files:
        d = _load_sim_with_slice_if_within(fp)
        if d is not None:
            parts.append(d)
    dfs["sim_events"] = pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()

    parts = []
    for fp in sim_pairs_files:
        d = _load_sim_with_slice_if_within(fp)
        if d is not None:
            parts.append(d)
    dfs["sim_pairs"] = pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()

    parts = [_load_obs_with_slice(fp) for fp in obs_events_files]
    dfs["obs_events"] = pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()

    parts = [_load_obs_with_slice(fp) for fp in obs_pairs_files]
    dfs["obs_pairs"] = pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()

    # ---------- write out ----------
    if write_out:
        out = base_dir / summary_folder
        out.mkdir(parents=True, exist_ok=True)
        for key, df in dfs.items():
            df.to_parquet(out / f"df_{key}.parquet", index=False)

        # Also save a manifest of exactly which files were read.
        manifest_rows = []
        for key, files in [
            ("sim_events", sim_events_files),
            ("sim_pairs", sim_pairs_files),
            ("obs_events", obs_events_files),
            ("obs_pairs", obs_pairs_files),
        ]:
            for fp in files:
                manifest_rows.append({
                    "kind": key,
                    "path": str(fp),
                    "slice": _parse_slice_from_path(fp),
                    "mc": _parse_mc_from_path(fp),
                })
        pd.DataFrame(manifest_rows).to_csv(out / "canonical_files_read_manifest.csv", index=False)

    # ---------- quick counts ----------
    if verbose:
        print(f"Canonical interaction directories used: {len(_canonical_interaction_dirs())}")
        print("Files read:")
        print(f"  sim_events: {len(sim_events_files)}")
        print(f"  sim_pairs : {len(sim_pairs_files)}")
        print(f"  obs_events: {len(obs_events_files)}")
        print(f"  obs_pairs : {len(obs_pairs_files)}")
        for key, df in dfs.items():
            if key.startswith("sim") and not df.empty and "MC_round" in df.columns:
                uniq_mc = sorted(pd.unique(df["MC_round"]))
                mc_info = f" | MC kept: {len(uniq_mc)} (min={min(uniq_mc)}, max={max(uniq_mc)})"
            else:
                mc_info = ""
            print(f"{key}: {len(df)} rows{mc_info}")

    return dfs


def audit_canonical_observed_files_for_pair(
    id_pair: Tuple[int, int],
    analysis_name: str = None,
    max_mc: int = 1000,
    bin_labels: List[str] = None,
) -> pd.DataFrame:
    """
    Optional sanity check: list canonical observed files only and verify that there
    is at most one file per pair × slice × kind × time_bin.
    """
    if analysis_name is None:
        analysis_name = MAIN_ANALYSIS_NAME if "MAIN_ANALYSIS_NAME" in globals() else "CRW_slice_RT_WIN1000_MC0001_1000"
    if bin_labels is None:
        bin_labels = globals().get("bin_labels", ["0-1h", "1h-1d", "1-2d", "2-4d", "4-8d", "8-16d", "16-21d"])

    id1, id2 = id_pair
    base_dir = pair_dir_hpc(id_pair, analysis_name=analysis_name) if "pair_dir_hpc" in globals() else Path(".")
    batch_label = f"MC0001_{int(max_mc):04d}"

    rows = []
    for sdir in sorted(Path(base_dir).glob("slice*")):
        int_dir = sdir / batch_label / "interactions"
        if not int_dir.exists():
            continue
        for kind in ["events", "pairs"]:
            for lbl in bin_labels:
                for fp in sorted(int_dir.glob(f"{id1}_{id2}_slice*_{kind}_{lbl}_observed_time.parquet")):
                    try:
                        n_rows = len(pd.read_parquet(fp))
                    except Exception:
                        n_rows = np.nan
                    rows.append({
                        "pair": f"{id1}_{id2}",
                        "slice": re.search(r"slice0*(\d+)", fp.name).group(0),
                        "kind": kind,
                        "time_bin": lbl,
                        "n_rows": n_rows,
                        "path": str(fp),
                    })

    out = pd.DataFrame(rows)
    if not out.empty:
        dup = out.groupby(["pair", "slice", "kind", "time_bin"]).size().reset_index(name="n_files")
        bad = dup[dup["n_files"] > 1]
        if len(bad):
            print("WARNING: duplicate canonical observed files found:")
            display(bad)
        else:
            print("No duplicate canonical observed files found.")
    return out

In [5]:
_mc_re = re.compile(r"(MC)(\d+)")
def _parse_slice_from_path(fp: Path) -> int:
    # ..._slice012_... -> 12 (0-based in your earlier utilities; keep consistent)
    stem = fp.stem
    tok = next(t for t in stem.split("_") if t.startswith("slice"))
    return int(tok.replace("slice", ""))

def _parse_mc_from_path(fp: Path) -> Optional[int]:
    stem = fp.stem
    for tok in stem.split("_"):
        if tok.startswith("MC"):
            try:
                return int(tok.replace("MC",""))
            except ValueError:
                return None
    return None

def _replace_timebin_in_name(fp: Path, new_label: str) -> Path:
    """Swap the time-bin token in the filename to new_label."""
    parts = fp.stem.split("_")
    # filename structure like: id1_id2_sliceXXX_(events|pairs)_{timebin}_MC#### or ..._observed_time
    # Find the token right after events|pairs
    for i, t in enumerate(parts):
        if t in ("events", "pairs"):
            # next token is the timebin, replace it
            parts[i+1] = new_label
            break
    return fp.with_name("_".join(parts) + fp.suffix)

def _merge_touching_events(df: pd.DataFrame, tol_seconds: int = 0) -> pd.DataFrame:
    """
    Merge adjacent events when previous end == current start for BOTH individuals.
    Assumes columns: p1, p2, p1_start, p1_end, p2_start, p2_end (datetime-like or str)
    """
    if df.empty:
        return df

    # ensure datetimes
    for col in ["p1_start","p1_end","p2_start","p2_end"]:
        if not np.issubdtype(df[col].dtype, np.datetime64):
            df[col] = pd.to_datetime(df[col], errors="coerce")

    df = df.sort_values(["p1","p2","p1_start","p2_start","p1_end","p2_end"]).reset_index(drop=True)

    out_rows = []
    cur = None
    tol = pd.Timedelta(seconds=tol_seconds)

    for _, row in df.iterrows():
        if cur is None:
            cur = row.copy()
            continue

        same_pair = (row["p1"] == cur["p1"]) and (row["p2"] == cur["p2"])
        touch_p1 = abs((row["p1_start"] - cur["p1_end"])) <= tol
        touch_p2 = abs((row["p2_start"] - cur["p2_end"])) <= tol

        if same_pair and touch_p1 and touch_p2:
            # extend current event
            cur["p1_end"] = max(cur["p1_end"], row["p1_end"])
            cur["p2_end"] = max(cur["p2_end"], row["p2_end"])
        else:
            out_rows.append(cur)
            cur = row.copy()

    if cur is not None:
        out_rows.append(cur)

    merged = pd.DataFrame(out_rows).reset_index(drop=True)

    # recompute duration metrics if you keep them (optional)
    # Example: total overlap minutes based on p1 timeline (or min of ends - max of starts)
    if "difference" in merged.columns:
        merged = merged.drop(columns=["difference"])
    merged["difference"] = (merged["p2_start"] - merged["p1_start"]).dt.total_seconds() / 60.0

    return merged

def _concat_pairs(files: List[Path]) -> pd.DataFrame:
    dfs = []
    for fp in files:
        d = pd.read_parquet(fp)
        dfs.append(d)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

def _concat_events(files: List[Path]) -> pd.DataFrame:
    dfs = []
    for fp in files:
        d = pd.read_parquet(fp)
        dfs.append(d)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

def scan_slices_and_mcs(
    id_pair: Tuple[int,int],
    base_dir: Path
) -> Tuple[List[int], List[int]]:
    """
    Find all slice indices and MC ids that exist for sub-day files.
    Returns (sorted_slices, sorted_mcs). Either may be empty.
    """
    id1, id2 = id_pair

    # build patterns WITHOUT regex alternation (glob can't do (events|pairs))
    patt_mc_events = [f"{id1}_{id2}_slice*_events_{lab}_MC*.parquet"  for lab in SUBDAY_LABELS]
    patt_mc_pairs  = [f"{id1}_{id2}_slice*_pairs_{lab}_MC*.parquet"   for lab in SUBDAY_LABELS]
    patt_obs_events= [f"{id1}_{id2}_slice*_events_{lab}_observed_time.parquet" for lab in SUBDAY_LABELS]
    patt_obs_pairs = [f"{id1}_{id2}_slice*_pairs_{lab}_observed_time.parquet"  for lab in SUBDAY_LABELS]

    def collect(patterns: List[str]) -> List[Path]:
        out = []
        for pat in patterns:
            out.extend(base_dir.rglob(pat))
        return out

    mc_files  = collect(patt_mc_events) + collect(patt_mc_pairs)
    obs_files = collect(patt_obs_events) + collect(patt_obs_pairs)

    slices, mcs = set(), set()

    for fp in mc_files:
        try:
            s = _parse_slice_from_path(fp)
            m = _parse_mc_from_path(fp)
        except StopIteration:
            continue
        if s is not None: slices.add(s)
        if m is not None: mcs.add(m)

    for fp in obs_files:
        try:
            s = _parse_slice_from_path(fp)
        except StopIteration:
            continue
        if s is not None: slices.add(s)

    return sorted(slices), sorted(mcs)

    
def combine_subday_bins_to_one_day_batched(
    id_pair: Tuple[int,int],
    base_dir: Path,
    batch_size: int = 50,
    dry_run: bool = False,
    tol_seconds: int = 0,
    verbose: bool = True,
) -> Dict[str, int]:
    """
    Same logic as before, but:
      - Detects (slices, MCs) present first
      - Iterates in order (slice asc, MC asc)
      - Buffers outputs and writes every `batch_size` files
    """
    id1, id2 = id_pair

    # Build lookups for quick file grouping
    def collect(patterns: List[str]) -> List[Path]:
        res = []
        for pat in patterns:
            res.extend(base_dir.rglob(pat))
        return res

    patt_mc_events = [f"{id1}_{id2}_slice*_events_{lab}_MC*.parquet"  for lab in SUBDAY_LABELS]
    patt_mc_pairs  = [f"{id1}_{id2}_slice*_pairs_{lab}_MC*.parquet"   for lab in SUBDAY_LABELS]
    patt_obs_events= [f"{id1}_{id2}_slice*_events_{lab}_observed_time.parquet" for lab in SUBDAY_LABELS]
    patt_obs_pairs = [f"{id1}_{id2}_slice*_pairs_{lab}_observed_time.parquet"  for lab in SUBDAY_LABELS]

    files_mc_events = collect(patt_mc_events)
    files_mc_pairs  = collect(patt_mc_pairs)
    files_obs_events= collect(patt_obs_events)
    files_obs_pairs = collect(patt_obs_pairs)

    # Group to dicts
    def key_mc(fp: Path):  return (_parse_slice_from_path(fp), _parse_mc_from_path(fp))
    def key_obs(fp: Path): return (_parse_slice_from_path(fp), "observed")

    grp_mc_events: Dict[tuple, List[Path]] = {}
    grp_mc_pairs : Dict[tuple, List[Path]] = {}
    grp_obs_events: Dict[tuple, List[Path]] = {}
    grp_obs_pairs : Dict[tuple, List[Path]] = {}

    for fp in files_mc_events: grp_mc_events.setdefault(key_mc(fp), []).append(fp)
    for fp in files_mc_pairs:  grp_mc_pairs.setdefault(key_mc(fp), []).append(fp)
    for fp in files_obs_events:grp_obs_events.setdefault(key_obs(fp), []).append(fp)
    for fp in files_obs_pairs: grp_obs_pairs.setdefault(key_obs(fp), []).append(fp)

    # Detect present slices and MCs
    slices, mcs = scan_slices_and_mcs(id_pair, base_dir)
    if verbose:
        if slices:
            slice_span = f"{min(slices)}–{max(slices)}"
        else:
            slice_span = "none"
    
        if mcs:
            mc_span = f"{min(mcs)}–{max(mcs)}"
            print(f"[scan] slices: {len(slices)} ({slice_span}), MCs: {len(mcs)} ({mc_span})")
        else:
            print(f"[scan] slices: {len(slices)} ({slice_span}), MCs: none (observed only?)")
    
    # Optional: bail early with a clearer message
    if not slices and not mcs:
        raise FileNotFoundError(
            f"No sub-day files found for pair {id_pair} under {base_dir}. "
            f"Checked labels: {SUBDAY_LABELS}"
        )


    # Write buffer
    buffer: List[Tuple[pd.DataFrame, Path, str]] = []  # (df, sample_fp, kind)
    written = 0
    skipped = 0

    def enqueue_write(df: pd.DataFrame, sample_fp: Path, kind: str):
        nonlocal skipped
        if df is None or df.empty:
            skipped += 1
            return
        out_fp = _replace_timebin_in_name(sample_fp, NEW_LABEL)
        buffer.append((df, out_fp, kind))

    def flush():
        nonlocal written
        if dry_run or not buffer:
            # nothing to write or dry-run just clears buffer
            buffer.clear()
            return
        for df, out_fp, kind in buffer:
            out_fp.parent.mkdir(parents=True, exist_ok=True)
            df.to_parquet(out_fp, index=False)
            if verbose:
                print(f"[write] {kind}: {out_fp}")
        written += len(buffer)
        buffer.clear()

    # ---- MC paths: iterate ordered (slice, MC) ----
    for s in slices:
        for m in mcs:
            k = (s, m)
            fl_pairs = grp_mc_pairs.get(k, [])
            fl_events= grp_mc_events.get(k, [])
            if not fl_pairs and not fl_events:
                continue

            # pairs: concat and tag
            if fl_pairs:
                dfp = _concat_pairs(sorted(fl_pairs))
                if not dfp.empty:
                    dfp["time_bin"] = NEW_LABEL
                enqueue_write(dfp, sorted(fl_pairs)[0], "pairs")

            # events: concat, merge touching, tag
            if fl_events:
                dfe = _concat_events(sorted(fl_events))
                if not dfe.empty:
                    dfe["time_bin"] = NEW_LABEL
                    dfe = _merge_touching_events(dfe, tol_seconds=tol_seconds)
                enqueue_write(dfe, sorted(fl_events)[0], "events")

            if len(buffer) >= batch_size:
                flush()

    # ---- Observed paths: iterate ordered by slice ----
    for s in slices:
        k = (s, "observed")
        fl_pairs = grp_obs_pairs.get(k, [])
        fl_events= grp_obs_events.get(k, [])
        if not fl_pairs and not fl_events:
            continue

        if fl_pairs:
            dfp = _concat_pairs(sorted(fl_pairs))
            if not dfp.empty:
                dfp["time_bin"] = NEW_LABEL
            enqueue_write(dfp, sorted(fl_pairs)[0], "pairs")

        if fl_events:
            dfe = _concat_events(sorted(fl_events))
            if not dfe.empty:
                dfe["time_bin"] = NEW_LABEL
                dfe = _merge_touching_events(dfe, tol_seconds=tol_seconds)
            enqueue_write(dfe, sorted(fl_events)[0], "events")

        if len(buffer) >= batch_size:
            flush()

    # final flush
    flush()

    if verbose:
        print(f"[combine_subday_bins_to_one_day_batched] base={base_dir} | written_files={written}, skipped_empty={skipped}")
    return {"written_files": written, "skipped_empty": skipped}

In [6]:
from scipy.stats import mannwhitneyu
from typing import List, Tuple, Dict, Any

# =============================================================================
# Direction / following-state helpers
# =============================================================================
# Interpretation used in the manuscript:
#   If tiger time is earlier  -> Leopard-following
#   If tiger time is later    -> Tiger-following

TIGER_ID_SET = {"131343", "229011", "229041", "229012", "229022", "229032"}
LEOPARD_ID_SET = {"31899", "31898", "37821", "37822", "37823"}


def _clean_id_value(x):
    """Convert IDs such as 229032, 229032.0, '229032.0' to '229032'."""
    if pd.isna(x):
        return None
    s = str(x).strip()
    try:
        f = float(s)
        if np.isfinite(f) and abs(f - round(f)) < 1e-9:
            return str(int(round(f)))
    except Exception:
        pass
    return s


def _animal_role(x):
    """Return 'tiger', 'leopard', or 'unknown'."""
    sid = _clean_id_value(x)
    if sid in TIGER_ID_SET:
        return "tiger"
    if sid in LEOPARD_ID_SET:
        return "leopard"

    # Fallback to paper labels if idcollar_mapping exists.
    mapping = globals().get("idcollar_mapping", {})
    lab = str(mapping.get(sid, sid))
    if lab.startswith(("FT", "MT")):
        return "tiger"
    if lab.startswith(("FL", "ML")):
        return "leopard"
    return "unknown"


def _canonical_pair_id_from_ids(a, b, id_pair=None):
    """
    Return pair ID in the canonical order used by folder names / home-range tables.
    If id_pair is provided, always use that order.
    """
    if id_pair is not None:
        return f"{int(id_pair[0])}_{int(id_pair[1])}"
    aa, bb = _clean_id_value(a), _clean_id_value(b)
    return f"{aa}_{bb}"


def add_following_state(df: pd.DataFrame, id_pair=None) -> pd.DataFrame:
    """
    Add ``following_state`` and ``tiger_delay_min`` to an events dataframe.

    tiger_delay_min = tiger_start_time - leopard_start_time.
      tiger_delay_min < 0  => tiger earlier  => Leopard-following
      tiger_delay_min > 0  => tiger later    => Tiger-following
      tiger_delay_min == 0 => Concurrent/colocation
    """
    out = df.copy()
    if out.empty:
        out["following_state"] = pd.Series(dtype="object")
        out["tiger_delay_min"] = pd.Series(dtype="float")
        return out

    # Ensure pair_id is clean/canonical for downstream merges.
    if id_pair is not None:
        out["pair_id"] = _canonical_pair_id_from_ids(None, None, id_pair=id_pair)
    elif {"p1", "p2"}.issubset(out.columns):
        out["pair_id"] = [
            _canonical_pair_id_from_ids(a, b, id_pair=None)
            for a, b in zip(out["p1"], out["p2"])
        ]

    tiger_delay = pd.Series(np.nan, index=out.index, dtype="float64")

    # Preferred path: compute from p1/p2 identities and their start times.
    if {"p1", "p2", "p1_start", "p2_start"}.issubset(out.columns):
        p1_start = pd.to_datetime(out["p1_start"], errors="coerce")
        p2_start = pd.to_datetime(out["p2_start"], errors="coerce")

        p1_role = out["p1"].map(_animal_role)
        p2_role = out["p2"].map(_animal_role)

        mask_p1_tiger = (p1_role == "tiger") & (p2_role == "leopard")
        mask_p2_tiger = (p2_role == "tiger") & (p1_role == "leopard")

        tiger_delay.loc[mask_p1_tiger] = (
            (p1_start.loc[mask_p1_tiger] - p2_start.loc[mask_p1_tiger])
            .dt.total_seconds() / 60.0
        )
        tiger_delay.loc[mask_p2_tiger] = (
            (p2_start.loc[mask_p2_tiger] - p1_start.loc[mask_p2_tiger])
            .dt.total_seconds() / 60.0
        )

    # Fallback: use difference = p2_start - p1_start and id_pair order.
    # In this project id_pair is tiger, leopard. If tiger is id1/p1:
    #   difference > 0 means leopard is later -> Leopard-following.
    if tiger_delay.isna().all() and "difference" in out.columns and id_pair is not None:
        diff = pd.to_numeric(out["difference"], errors="coerce")
        id1_role = _animal_role(id_pair[0])
        id2_role = _animal_role(id_pair[1])
        if id1_role == "tiger" and id2_role == "leopard":
            tiger_delay = -diff  # tiger_start - leopard_start = - (p2 - p1)
        elif id2_role == "tiger" and id1_role == "leopard":
            tiger_delay = diff

    out["tiger_delay_min"] = tiger_delay
    # Rule:
    # tiger_delay_min = tiger_time - leopard_time
    # tiger_delay_min < 0  means tiger was earlier, so leopard is following
    # tiger_delay_min > 0  means tiger was later, so tiger is following
    following_state = pd.Series(pd.NA, index=out.index, dtype="object")
    
    following_state.loc[tiger_delay < 0] = "Leopard-following"      # tiger earlier
    following_state.loc[tiger_delay > 0] = "Tiger-following"        # tiger later
    following_state.loc[tiger_delay == 0] = "Concurrent/colocation"
    
    out["following_state"] = following_state

    return out


def audit_following_direction(df_events: pd.DataFrame, id_pair, bin_labels=None, name="events") -> pd.DataFrame:
    """Diagnostic table to verify Tiger/Leopard-following direction labels."""
    d = add_following_state(df_events, id_pair=id_pair)
    if d.empty:
        return pd.DataFrame(columns=["source", "pair_id", "slice", "time_bin", "following_state", "n"])

    # Normalize time_bin/slice for display.
    if "time_bin" in d.columns:
        d["time_bin"] = d["time_bin"].astype(str).str.replace("–", "-", regex=False).str.replace("—", "-", regex=False).str.strip()
    if "slice" in d.columns:
        d["slice"] = pd.to_numeric(d["slice"], errors="coerce").astype("Int64")

    grp = (
        d.groupby(["pair_id", "slice", "time_bin", "following_state"], dropna=False)
         .size()
         .rename("n")
         .reset_index()
    )
    grp.insert(0, "source", name)
    return grp

In [7]:
def compute_pvalues_duration_empirical(
    df_sim: pd.DataFrame,
    df_obs: pd.DataFrame,
    slices: List[str],
    time_bin: str,
    tail: str = "greater"
) -> pd.DataFrame:
    """
    For each slice, compares total duration per MC_run vs observed total duration
    using an empirical p-value.

    tail:
      - "greater": p = P(sim_sums >= obs_sum)
      - "less":    p = P(sim_sums <= obs_sum)
      - "two-sided": p = P(|sim_sums - median(sim_sums)| >= |obs_sum - median(sim_sums)|)
    """
    rows: List[Dict[str, Any]] = []
    for sl in slices:
        # simulated total duration per MC_run
        sim = df_sim[(df_sim['slice']==sl) & (df_sim['time_bin']==time_bin)]
        sim_sums = sim.groupby('MC_round')['duration'].sum().values

        # skip if no simulated runs
        if len(sim_sums) == 0:
            continue
        
        # observed total duration (default to 0 if no column or no rows)
        if 'duration' in df_obs.columns:
            obs = df_obs[(df_obs['slice']==sl) & (df_obs['time_bin']==time_bin)]
            obs_sum = obs['duration'].sum()  # zero if none
            obs_count = len(obs)  # zero if none
        else:
            obs_sum = 0.0
            obs_count = 0
        
        n = len(sim_sums)
        if tail == "greater":
            k = np.count_nonzero(sim_sums >= obs_sum)
            p = (k + 1) / (n + 1)
        elif tail == "less":
            k = np.count_nonzero(sim_sums <= obs_sum)
            p = (k + 1) / (n + 1)
        else:  # two-sided
            med = np.median(sim_sums)
            diffs = np.abs(sim_sums - med)
            obs_diff = abs(obs_sum - med)
            k = np.count_nonzero(diffs >= obs_diff)
            p = (k + 1) / (n + 1)
        
        rows.append({
            'slice': sl,
            'time_bin': time_bin,
            'sim_median': np.median(sim_sums),
            'obs_sum': obs_sum,
            'obs_count': obs_count,
            'p_value': p,
            'significant': (p < 0.01)
        })
        
    return pd.DataFrame(rows)

In [8]:
def compute_pvalues_event_counts_by_leader(
    df_sim: pd.DataFrame,
    df_obs: pd.DataFrame,
    slices: List[str],
    bin_labels: List[str],
    id_pair: Tuple[int, int] = None,
) -> pd.DataFrame:
    """
    Computes Mann-Whitney U p-values per slice, time_bin, and following state.

    Direction rule:
      tiger earlier -> Leopard-following
      tiger later   -> Tiger-following
    """
    sim = add_following_state(df_sim, id_pair=id_pair)
    obs = add_following_state(df_obs, id_pair=id_pair)

    rows: List[Dict[str, Any]] = []
    for sl in slices:
        for lbl in bin_labels:
            for state in ["Leopard-following", "Tiger-following"]:
                sim_sel = sim[
                    (sim["slice"] == sl) &
                    (sim["time_bin"] == lbl) &
                    (sim["following_state"] == state)
                ]
                sim_counts = sim_sel.groupby("MC_round").size().values

                # If no simulated runs for this state/bin, keep a row with p=NaN.
                obs_sel = obs[
                    (obs["slice"] == sl) &
                    (obs["time_bin"] == lbl) &
                    (obs["following_state"] == state)
                ]
                obs_count = len(obs_sel)

                if len(sim_counts) == 0:
                    rows.append({
                        "slice": sl,
                        "time_bin": lbl,
                        "leader": state,
                        "following_state": state,
                        "n_sim": 0,
                        "n_obs": obs_count,
                        "U": np.nan,
                        "p_value": np.nan,
                        "significant": False,
                    })
                    continue

                obs_array = np.full(len(sim_counts), obs_count)
                U, p = mannwhitneyu(sim_counts, obs_array, alternative="two-sided")

                rows.append({
                    "slice": sl,
                    "time_bin": lbl,
                    "leader": state,              # kept for backward compatibility
                    "following_state": state,
                    "n_sim": len(sim_counts),
                    "n_obs": obs_count,
                    "U": U,
                    "p_value": p,
                    "significant": (p < 0.01),
                })

    return pd.DataFrame(rows)

In [9]:
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from typing import List, Tuple, Union, Sequence, Optional
from matplotlib.transforms import blended_transform_factory

def plot_slicewise_threepanel(
    df_sim_events: pd.DataFrame,
    df_obs_events: pd.DataFrame,
    id_pair: Tuple[int,int],
    bin_labels: List[str],
    concurrent_bin: str = "0-1h",
    slices: Union[None, Sequence[str]] = None,
    bins: int = 20,
    figsize_per_row: Tuple[int,int] = (9, 3),
    title_fs: int = 14,
    label_fs: int = 12,
    tick_fs: int = 10,
    star_fs: int = 40,
    legend_fs: int = 12,
    save_path: Optional[Union[str, Path]] = None,
    show: bool = False
):
    """
    For each slice, produce three side-by-side plots:
      1) Concurrent duration histogram (sim vs obs)
      2) Event frequency boxplots for tiger-leading (difference > 0)
      3) Event frequency boxplots for leopard-leading (difference < 0)

    Parameters
    ----------
    df_sim_events : DataFrame with ['slice','time_bin','MC_round','duration','difference']
    df_obs_events : DataFrame with ['slice','time_bin','duration','difference']
    id_pair : (id1,id2)
    bin_labels : ordered list of time-bin labels for the boxplots
    concurrent_bin : time-bin for the duration histogram
    slices : list of slice labels; defaults to sorted unique df_sim_events['slice']
    bins : number of bins for histogram
    figsize_per_row : tuple (width, height) per row
    """
    if slices is None:
        slices = sorted(df_sim_events['slice'].unique())

    # Precompute all p-values
    # pv_dur = compute_pvalues_duration(df_sim_events, df_obs_events, slices, concurrent_bin)
    pv_dur = compute_pvalues_duration_empirical(df_sim_events, df_obs_events, slices, concurrent_bin)
    print(pv_dur)
    # Add robust following-state labels before direction-specific panels
    df_sim_events = add_following_state(df_sim_events, id_pair=id_pair)
    df_obs_events = add_following_state(df_obs_events, id_pair=id_pair)
    pv_evt = compute_pvalues_event_counts_by_leader(df_sim_events, df_obs_events, slices, bin_labels, id_pair=id_pair)
    print(pv_evt)

    # delayed bins (exclude concurrent) for panels 2 & 3
    delayed_labels = [lbl for lbl in bin_labels if lbl != concurrent_bin]

    n = len(slices)
    ind = np.arange(len(delayed_labels))
    width = 0.35
    
    fig, axes = plt.subplots(n, 3,
                             figsize=(3*figsize_per_row[0], n*figsize_per_row[1]),
                             squeeze=False)
    
    id1, id2 = id_pair

    # 3) Precompute histogram y-limit
    hist_maxes = []
    for s0 in slices:
        # get the sim sums
        sim_con = (
            df_sim_events
            .loc[(df_sim_events['slice']==s0) & (df_sim_events['time_bin']==concurrent_bin)]
            .groupby('MC_round')['duration']
            .sum()
        )
        if not sim_con.empty:
            counts, _ = np.histogram(sim_con, bins=bins)
            hist_maxes.append(counts.max())
    
    # now take the overall max + a little padding
    hist_ymax = max(hist_maxes) * 1.05 if hist_maxes else 1

    # 4) Precompute boxplot y-limit
    box_counts_all = []
    for s0 in slices:
        # tiger
        mask_ts = ((df_sim_events['slice']==s0) & (df_sim_events['following_state']=='Leopard-following'))
        g_t = (
            df_sim_events[mask_ts]
            .groupby(['time_bin','MC_round'])
            .size()
        )
        box_counts_all.extend(g_t.values.tolist())
        # obs tiger
        for lbl in delayed_labels:
            box_counts_all.append(
                len(df_obs_events.loc[
                    (df_obs_events['slice']==s0) &
                    (df_obs_events['following_state']=='Leopard-following') &
                    (df_obs_events['time_bin']==lbl)
                ])
            )
        # leopard
        mask_ls = ((df_sim_events['slice']==s0) & (df_sim_events['following_state']=='Tiger-following'))
        g_l = (
            df_sim_events[mask_ls]
            .groupby(['time_bin','MC_round'])
            .size()
        )
        box_counts_all.extend(g_l.values.tolist())
        # obs leopard
        for lbl in delayed_labels:
            box_counts_all.append(
                len(df_obs_events.loc[
                    (df_obs_events['slice']==s0) &
                    (df_obs_events['following_state']=='Tiger-following') &
                    (df_obs_events['time_bin']==lbl)
                ])
            )
    box_ymax = max(box_counts_all)*1.05 if box_counts_all else 1

    # 5) Global histogram x‐limit
    all_maxes = []
    for s0 in slices:
        sim_con = (
            df_sim_events
            .loc[(df_sim_events['slice']==s0) & (df_sim_events['time_bin']==concurrent_bin)]
            .groupby('MC_round')['duration']
            .sum()
        )
        if not sim_con.empty:
            all_maxes.append(sim_con.max())
        if 'duration' in df_obs_events.columns:
            mask_obs = (
                (df_obs_events['slice']    == s0) &
                (df_obs_events['time_bin'] == concurrent_bin)
            )
            obs_values = df_obs_events.loc[mask_obs, 'duration']
            obs_sum = obs_values.sum() if not obs_values.empty else 0.0
        else:
            obs_sum = 0.0
    
        all_maxes.append(obs_sum)
    global_max = max(all_maxes) if all_maxes else 0
    xlim = (0, global_max*1.05)
    

    for i, sl in enumerate(slices):
        ax0, ax1, ax2 = axes[i]

        # --------------------------------------------------
        # 1) Concurrent duration histogram
        sim_con = df_sim_events[(df_sim_events['slice']==sl) & (df_sim_events['time_bin']==concurrent_bin)]
        sim_con_sum = sim_con.groupby('MC_round')['duration'].sum()
        # safe observed duration
        if 'duration' in df_obs_events.columns:
            mask_obs = (
                (df_obs_events['slice']    == sl) &
                (df_obs_events['time_bin'] == concurrent_bin)
            )
            obs_values = df_obs_events.loc[mask_obs, 'duration']
            obs_con_sum = obs_values.sum() if not obs_values.empty else 0.0
        else:
            obs_con_sum = 0.0
        
        ax0.hist(sim_con_sum, bins=bins, alpha=0.7, edgecolor='k', color='#986eac', label='Sim')
        ax0.axvline(obs_con_sum, color='C1', lw=2, label='Obs')
        ax0.set_title(f"Partition {sl}\nConcurrent Duration", fontsize=title_fs)
        ax0.set_xlabel("Duration (min)", fontsize=label_fs)
        ax0.set_ylabel("Count", fontsize=label_fs)
        ax0.tick_params(labelsize=tick_fs)
        ax0.set_xlim(-10, xlim[1])
        ax0.set_ylim(0, hist_ymax)

        if i == 0:
            ax0.legend(loc='upper right', fontsize=legend_fs)
            
        # annotate star if significant
        row_d = pv_dur[pv_dur['slice']==sl]
        if not row_d.empty and row_d.iloc[0]['significant']:
            ax0.text(0.02, 0.99, '*', transform=ax0.transAxes,
                     fontsize=star_fs, color='red', va='top', ha='left',
                    fontweight='bold', zorder=10)

        # --------------------------------------------------
        # Prepare count data for boxplots
        def prepare_counts(df, leader_cond):
            sel = df[(df['slice']==sl) & leader_cond(df)]
            counts = sel.groupby(['time_bin','MC_round']).size().reset_index(name='count')
            return [counts.loc[counts['time_bin']==lbl, 'count'].values for lbl in delayed_labels]

        sim_data_t = prepare_counts(df_sim_events,  lambda df: df['following_state'] == 'Leopard-following')
        obs_counts_t = df_obs_events[(df_obs_events['slice']==sl) & (df_obs_events['following_state'] == 'Leopard-following')]
        obs_data_t = [np.array([len(obs_counts_t[obs_counts_t['time_bin']==lbl])]) for lbl in delayed_labels]

        sim_data_l = prepare_counts(df_sim_events,  lambda df: df['following_state'] == 'Tiger-following')
        obs_counts_l = df_obs_events[(df_obs_events['slice']==sl) & (df_obs_events['following_state'] == 'Tiger-following')]
        obs_data_l = [np.array([len(obs_counts_l[obs_counts_l['time_bin']==lbl])]) for lbl in delayed_labels]

        # # y-limit
        # all_counts = np.hstack([
        #     np.hstack(sim_data_t) if len(sim_data_t)>0 else [0],
        #     np.hstack(obs_data_t),
        #     np.hstack(sim_data_l) if len(sim_data_l)>0 else [0],
        #     np.hstack(obs_data_l)
        # ])
        # ymax = max(all_counts.max()* 1.05, 1)

        # --------------------------------------------------
        # 2) Tiger-leading boxplots (difference > 0)
        ax1.boxplot(sim_data_t, positions=ind-width/2, widths=width,
                    patch_artist=True, boxprops=dict(facecolor='#686EE2', edgecolor='k'),
                   medianprops=dict(color='k'))
        ax1.boxplot(obs_data_t, positions=ind+width/2, widths=width,
                    patch_artist=True, boxprops=dict(facecolor='C1', edgecolor='k'))
        ax1.set_title(f"Partition {sl} Leopard-following\nEvent Frequency", fontsize=title_fs)
        ax1.set_ylim(-10, box_ymax)
        ax1.set_xticks(ind)
        ax1.set_xticklabels(delayed_labels, rotation=45, ha='right')
        ax1.set_xlabel("Time lag", fontsize=label_fs)
        ax1.set_ylabel("Frequency", fontsize=label_fs)
        ax1.tick_params(labelsize=tick_fs)
        if i == 0:
            legend_handles = [Patch(facecolor='#0072b2', edgecolor='k', label='Sim'),
                              Line2D([0], [0], color='C1', lw=2, label='Obs')]
            ax1.legend(handles=legend_handles, loc='upper right', fontsize=legend_fs)

        # annotate stars per bin
        for j, lbl in enumerate(delayed_labels):
            pv_row = pv_evt[
                (pv_evt['slice']==sl) &
                (pv_evt['time_bin']==lbl) &
                (pv_evt['following_state']=='Leopard-following')
            ]
            if not pv_row.empty and pv_row.iloc[0]['significant']:
                # place star just above the highest box
                trans1 = blended_transform_factory(ax1.transData, ax1.transAxes)
                ax1.text(ind[j], 0.99, '*',
                         transform=trans1,
                         ha='center', va='top', fontsize=star_fs, color='red',
                         fontweight='bold', zorder=10)
            
        # --------------------------------------------------
        # 3) Leopard-leading boxplots (difference < 0)        
        ax2.boxplot(sim_data_l, positions=ind-width/2, widths=width,
                    patch_artist=True, boxprops=dict(facecolor='#F35C6E', edgecolor='k'),
                   medianprops=dict(color='k'))
        ax2.boxplot(obs_data_l, positions=ind+width/2, widths=width,
                    patch_artist=True, boxprops=dict(facecolor='C1', edgecolor='k'))
        ax2.set_title(f"Partition {sl} Tiger-following\nEvent Frequency ", fontsize=title_fs)
        ax2.set_ylim(-10, box_ymax)
        ax2.set_xticks(ind)
        ax2.set_xticklabels(delayed_labels, rotation=45, ha='right')
        ax2.set_xlabel("Time lag", fontsize=label_fs)
        ax2.tick_params(labelsize=tick_fs)
        if i == 0:
            legend_handles = [Patch(facecolor='#d55e00', edgecolor='k', label='Sim'),
                              Line2D([0], [0], color='C1', lw=2, label='Obs')]
            ax2.legend(handles=legend_handles, loc='upper right', fontsize=legend_fs)

        # annotate stars per bin
        for j, lbl in enumerate(delayed_labels):
                pv_row = pv_evt[
                    (pv_evt['slice']==sl) &
                    (pv_evt['time_bin']==lbl) &
                    (pv_evt['following_state']=='Tiger-following')
                ]
                if not pv_row.empty and pv_row.iloc[0]['significant']:
                    trans2 = blended_transform_factory(ax2.transData, ax2.transAxes)
                    ax2.text(ind[j], 0.99, '*',
                             transform=trans2,
                             ha='center', va='top', fontsize=star_fs, color='red',
                             fontweight='bold', zorder=10)
    plt.tight_layout()

    # ---------------------------------------------------------
    # Force all count/duration axes in null-model figure to start at 0
    # Put this inside plot_slicewise_threepanel(), immediately before savefig
    # ---------------------------------------------------------
    for ax in fig.axes:
        if not ax.has_data():
            continue
    
        ymin, ymax = ax.get_ylim()
    
        if not np.isfinite(ymin) or not np.isfinite(ymax):
            continue
    
        if ymin < 0:
            bottom_pad = 0.03 * ymax if ymax > 0 else 0.2
            top_pad = 0.05 * ymax if ymax > 0 else 0.5
    
            ax.set_ylim(bottom=-bottom_pad, top=ymax + top_pad)
    
            ticks = ax.get_yticks()
            ax.set_yticks([t for t in ticks if t >= 0])

    if save_path is not None:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=500, bbox_inches='tight')
    else:
        out_path = Path(f"../../figure/{id_pair[0]}_{id_pair[1]}_null_model_star.jpg")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=500, bbox_inches='tight')

    if show:
        plt.show()
    else:
        plt.close(fig)
    return fig

In [10]:
import re
from pathlib import Path
from typing import Tuple, List, Optional, Dict
import pandas as pd
import numpy as np

id_pair = (229032, 37821)
bin_labels = ["0-1h", "1h-1d","1-2d","2-4d","4-8d","8-16d", "16-21d"]
time_bins   = [0, 60, 1440, 2880, 5760, 11520, 23040, 30240]
id1, id2 = id_pair
base_dir1 = Path(f"../../simulated_trajectory/CRW_slice_RT_WIN1000_MC0001_1000/by_slice_{id1}_{id2}_reverse_time")

## Figure 2: Home Range, Tracking Data Density and Number

In [11]:
import os
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from datetime import timedelta
from typing import List, Tuple

In [12]:
def extract_adjusted_tracking_data(file_path, id_pair, output_path):
    """
    Extracts the tracking data within the adjusted shared timeline.
    - Keeps three weeks before the shared start time for early starters (if possible).
    - Keeps three weeks after the shared end time for late finishers (if possible).
    - If the time difference is less than three weeks, keeps the original data.
    """
    # Load the dataset
    df = pd.read_csv(file_path)

    # Convert time column to datetime format
    df['Time_LMT'] = pd.to_datetime(df['Time_LMT'])

    # Filter for the selected individuals
    df_pair = df[df['idcollar'].isin(id_pair)].copy()

    # Find the earliest and latest tracking times for each individual
    earliest_times = df_pair.groupby('idcollar')['Time_LMT'].min()
    latest_times = df_pair.groupby('idcollar')['Time_LMT'].max()

    # Determine the shared start and end times
    shared_earliest_time = earliest_times.max()
    shared_latest_time = latest_times.min()

    # Apply a three-week buffer for early starters
    adjusted_start_times = {}
    for id in id_pair:
        individual_start = earliest_times[id]
        if (shared_earliest_time - individual_start) > pd.Timedelta(weeks=0):
            adjusted_start_times[id] = shared_earliest_time - pd.Timedelta(weeks=0)
        else:
            adjusted_start_times[id] = individual_start  # Keep original if within three weeks

    # Apply a three-week buffer for late finishers
    adjusted_end_times = {}
    for id in id_pair:
        individual_end = latest_times[id]
        if (individual_end - shared_latest_time) > pd.Timedelta(weeks=0):
            adjusted_end_times[id] = shared_latest_time + pd.Timedelta(weeks=0)
        else:
            adjusted_end_times[id] = individual_end  # Keep original if within three weeks

    # Extract rows within the adjusted timeline for each individual
    df_filtered = pd.concat([
        df_pair[(df_pair['idcollar'] == id) &
                (df_pair['Time_LMT'] >= adjusted_start_times[id]) &
                (df_pair['Time_LMT'] <= adjusted_end_times[id])]
        for id in id_pair
    ])

    # Sort by time for proper sequence
    df_filtered = df_filtered.sort_values(by=['Time_LMT'])

    # Save the extracted dataset
    df_filtered[['idcollar', 'Time_LMT', 'proj_lon', 'proj_lat', 'slope', 'sb', 'bt', 'gr']].to_csv(
        output_path, index=False
    )

    print(f"Extracted tracking data saved to {output_path}")

    return df_filtered  # Return the filtered DataFrame

In [13]:
def compute_slice_home_ranges(
    file_path: str,
    id_pairs: List[Tuple[int,int]],
    adjusted_dir: str,
    window_hours: int = 1000,
    utm_epsg: int = 32647
)-> Tuple[gpd.GeoDataFrame, gpd.GeoDataFrame]:
    """
    For each pair in id_pairs:
      1) Runs extract_adjusted_tracking_data into adjusted_dir
      2) Loads and renames columns
      3) Splits into reverse-time windows of window_hours
      4) Computes per-idcollar:
         - number of points
         - 95% MCP area (km2) and polygon
      5) Computes overlapped MCP area for the two individuals (km2)
    Returns GeoDataFrame with columns:
      pair_id, idcollar, slice, start, end,
      n_points, area_km2, overlapped_area_km2, geometry
    """
    records = []

    for id1, id2 in id_pairs:
        pair_id = f"{id1}_{id2}"
        adj_csv = os.path.join(adjusted_dir, f"adjusted_timeline_{id1}_{id2}.csv")

        # 1) extract & save adjusted timeline
        df_full = extract_adjusted_tracking_data(file_path, [id1, id2], adj_csv)
        # 2) preprocess
        df_full["time"] = pd.to_datetime(df_full["Time_LMT"], errors="coerce")
        df_full = df_full.rename(columns={"idcollar": "idcollar"})

        # 3) build reverse-time windows
        start, end = df_full["time"].min(), df_full["time"].max()
        window = timedelta(hours=window_hours)
        rev = []
        cur_end = end
        while True:
            cur_start = cur_end - window
            if cur_start < start:
                break
            rev.append((cur_start, cur_end))
            cur_end = cur_start
        windows = list(reversed(rev))

        # 4) convert to GeoDataFrame & project
        gdf = gpd.GeoDataFrame(
            df_full,
            geometry=gpd.points_from_xy(df_full["longitude"], df_full["latitude"]),
            crs="EPSG:4326"
        ).to_crs(epsg=utm_epsg)

        # 5) loop slices
        for slice_idx, (w0, w1) in enumerate(windows):
            df_slice = gdf[(gdf["time"]>=w0)&(gdf["time"]<w1)]
            if df_slice.empty:
                continue

            # Compute each individual's MCP in this slice
            mcp_polys = {}
            counts     = {}
            for indiv in (id1, id2):
                pts = df_slice[df_slice["idcollar"]==indiv]
                n_pts = len(pts)
                if n_pts < 3:
                    mcp_polys[indiv] = None
                    counts[indiv]    = n_pts
                    continue

                # 95% MCP
                cen    = pts.unary_union.centroid
                pts["dist"] = pts.geometry.distance(cen)
                thresh = pts["dist"].quantile(0.95)
                core   = pts[pts["dist"] <= thresh]
                poly   = core.unary_union.convex_hull
                mcp_polys[indiv] = poly
                counts[indiv]    = n_pts

            # Compute overlapped area if both MCPs exist
            if mcp_polys[id1] and mcp_polys[id2]:
                overlap = mcp_polys[id1].intersection(mcp_polys[id2])
                overlapped_area = overlap.area / 1e6
            else:
                overlapped_area = 0.0

            # 6) emit one record per individual, carrying overlap area
            for indiv in (id1, id2):
                poly = mcp_polys[indiv]
                if poly is None:
                    continue
                records.append({
                    "pair_id":            pair_id,
                    "idcollar":           indiv,
                    "slice":              slice_idx + 1,
                    "start":              w0,
                    "end":                w1,
                    "n_points":           counts[indiv],
                    "area_km2":           poly.area / 1e6,
                    "overlapped_area_km2": overlapped_area,
                    "geometry":           poly
                })

    # assemble GeoDataFrame
    result = gpd.GeoDataFrame(records, crs=gdf.crs)
    return result

In [57]:
import os
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from datetime import timedelta
from typing import List, Tuple

def compute_slice_home_ranges_with_points(
    file_path: str,
    id_pairs: List[Tuple[int,int]],
    adjusted_dir: str,
    window_hours: int = 1000,
    utm_epsg: int = 32647
) -> Tuple[gpd.GeoDataFrame, gpd.GeoDataFrame]:
    """
    Extends compute_slice_home_ranges:
      - Returns two GeoDataFrames:
        1) MCP boundaries per (pair, indiv, slice)
        2) Tracking points per (pair, indiv, slice)
    """
    boundary_records = []
    point_records = []

    for id1, id2 in id_pairs:
        pair_id = f"{id1}_{id2}"
        adj_csv = os.path.join(adjusted_dir, f"adjusted_timeline_{id1}_{id2}.csv")
        df_full = extract_adjusted_tracking_data(file_path, [id1, id2], adj_csv)
        df_full["time"] = pd.to_datetime(df_full["Time_LMT"], errors="coerce")
        # windows
        start, end = df_full["time"].min(), df_full["time"].max()
        window = timedelta(hours=window_hours)
        rev, cur_end = [], end
        while True:
            cur_start = cur_end - window
            if cur_start < start: break
            rev.append((cur_start, cur_end))
            cur_end = cur_start
        windows = list(reversed(rev))
        # project points
        gdf = gpd.GeoDataFrame(
            df_full, geometry=gpd.points_from_xy(df_full["longitude"], df_full["latitude"]),
            crs="EPSG:4326"
        ).to_crs(epsg=utm_epsg)
        for slice_idx, (w0, w1) in enumerate(windows):
            df_slice = gdf[(gdf["time"]>=w0)&(gdf["time"]<w1)]
            if df_slice.empty: continue
            # record points
            for _, row in df_slice.iterrows():
                point_records.append({
                    "pair_id": pair_id,
                    "idcollar": row["idcollar"],
                    "slice": slice_idx + 1,
                    "geometry": row.geometry
                })
            # compute MCP per individual
            mcp_polys, counts = {}, {}
            for indiv in (id1, id2):
                pts = df_slice[df_slice["idcollar"]==indiv]
                n_pts = len(pts)
                counts[indiv] = n_pts
                if n_pts < 3:
                    mcp_polys[indiv] = None
                    counts[indiv]    = n_pts
                    continue
                # # 95% MCP
                # cen = pts.unary_union.centroid
                # pts["dist"] = pts.geometry.distance(cen)
                # core = pts[pts["dist"] <= pts["dist"].quantile(0.95)]
                # poly = core.unary_union.convex_hull
                # mcp_polys[indiv] = poly
                # counts[indiv]    = n_pts

                # 100% MCP using all observed points in this partition
                poly = pts.unary_union.convex_hull
                mcp_polys[indiv] = poly
                counts[indiv] = n_pts
                            
            # Compute overlapped area if both MCPs exist
            overlap = None
            if mcp_polys[id1] and mcp_polys[id2]:
                overlap = mcp_polys[id1].intersection(mcp_polys[id2])
                overlapped_area = overlap.area / 1e6
            else:
                overlapped_area = 0.0

            # 6) emit one record per individual, carrying overlap area
            for indiv in (id1, id2):
                poly = mcp_polys[indiv]
                if poly is None: continue
                boundary_records.append({
                    "pair_id": pair_id,
                    "idcollar": indiv,
                    "slice": slice_idx + 1,
                    "start": w0,
                    "end": w1,
                    "n_points": counts[indiv],
                    "area_km2": poly.area / 1e6,
                    "overlapped_area_km2": overlapped_area,
                    "geometry": poly
                })
    

    boundary_gdf = gpd.GeoDataFrame(boundary_records, crs=gdf.crs)
    point_gdf = gpd.GeoDataFrame(point_records, crs=gdf.crs)
    return boundary_gdf, point_gdf

In [58]:
def integrate_event_counts(
    df_obs_events: pd.DataFrame,
    gdf_slices,
    time_bins: List[str],
    id_pair: Tuple[int, int] = None,
):
    """
    Build a full pair × slice × time_bin table with observed event counts.
    Robust to empty observed events and p1/p2 stored as floats.
    """
    # Cross-join gdf_slices with final time bins first. This guarantees all bins exist.
    base = gdf_slices.reset_index(drop=True).copy()
    tb_df = pd.DataFrame({"time_bin": time_bins})
    base["key"] = 1
    tb_df["key"] = 1
    expanded = base.merge(tb_df, on="key").drop("key", axis=1)
    expanded["pair_id"] = expanded["pair_id"].astype(str)
    expanded["slice"] = pd.to_numeric(expanded["slice"], errors="coerce").astype("Int64")
    expanded["time_bin"] = expanded["time_bin"].astype(str)

    if df_obs_events is None or df_obs_events.empty:
        expanded["n_events"] = 0
        return gpd.GeoDataFrame(expanded, geometry="geometry", crs=gdf_slices.crs)

    df = add_following_state(df_obs_events.copy(), id_pair=id_pair)
    if "slice" in df.columns:
        df["slice"] = pd.to_numeric(df["slice"], errors="coerce").astype("Int64")
    if "time_bin" in df.columns:
        df["time_bin"] = (
            df["time_bin"].astype(str)
            .str.replace("–", "-", regex=False)
            .str.replace("—", "-", regex=False)
            .str.strip()
        )
    if id_pair is not None:
        df["pair_id"] = _canonical_pair_id_from_ids(None, None, id_pair=id_pair)
    elif "pair_id" not in df.columns and {"p1", "p2"}.issubset(df.columns):
        df["pair_id"] = [
            _canonical_pair_id_from_ids(a, b, id_pair=None)
            for a, b in zip(df["p1"], df["p2"])
        ]

    grp = (
        df.groupby(["pair_id", "slice", "time_bin"], dropna=False)
          .size()
          .reset_index(name="n_events")
    )
    grp["pair_id"] = grp["pair_id"].astype(str)
    grp["slice"] = pd.to_numeric(grp["slice"], errors="coerce").astype("Int64")
    grp["time_bin"] = grp["time_bin"].astype(str)

    merged = expanded.merge(grp, on=["pair_id", "slice", "time_bin"], how="left")
    merged["n_events"] = merged["n_events"].fillna(0).astype(int)

    return gpd.GeoDataFrame(merged, geometry="geometry", crs=gdf_slices.crs)

In [16]:
import matplotlib.pyplot as plt
import numpy as np
import geopandas as gpd
import contextily as ctx
from scipy.stats import gaussian_kde
from shapely.geometry import Point
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrow
from matplotlib_scalebar.scalebar import ScaleBar  # requires matplotlib_scalebar package
from typing import Tuple

def plot_slices_hr_kde_grid(
    boundary_gdf: gpd.GeoDataFrame,
    point_gdf: gpd.GeoDataFrame,
    id_pair: Tuple[int,int],
    padding_frac: float = 0.05,
    kde_grid_size: int = 100
):
    """
    For each slice of a given pair, subplot:
      - MCP boundary (red vs blue outline)
      - KDE of points for each individual, clipped to that individual's MCP polygon
      - Shared dynamic grid (2-4 cols based on slice count)
      - Per-panel 2 km scale bar and north arrow
      - Basemap from OpenStreetMap (fallback to gray)
      - Legend of individuals in upper right
    """
    id1, id2 = id_pair
    label1 = idcollar_mapping.get(str(id1), str(id1))
    label2 = idcollar_mapping.get(str(id2), str(id2))
    pair = f"{id1}_{id2}"

    # Project to WebMercator for consistent meters units
    b3857 = boundary_gdf.to_crs(epsg=3857)
    p3857 = point_gdf.to_crs(epsg=3857)

    # global bounds
    all_polys = b3857.query("pair_id==@pair")['geometry']
    if all_polys.empty:
        raise ValueError(f"No MCP data for pair {pair}")
    minx, miny, maxx, maxy = all_polys.unary_union.bounds
    # Add a bit of padding
    pad_x = (maxx - minx) * padding_frac
    pad_y = (maxy - miny) * padding_frac
    minx, maxx = minx - pad_x, maxx + pad_x
    miny, maxy = miny - pad_y, maxy + pad_y

    # Unique slices for this pair
    slices = sorted(b3857.query("pair_id==@pair")['slice'].unique())
    n_slices = len(slices)
    if n_slices == 0:
        raise ValueError(f"No data for pair {pair}")

    # Determine columns: <=16→4, <=25→5, else→6
    if n_slices <= 16:
        n_cols = 4
    elif n_slices <= 25:
        n_cols = 5
    else:
        n_cols = 6
    n_rows = int(np.ceil(n_slices / n_cols))

    # Set up figure
    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(5*n_cols, 5*n_rows),
        constrained_layout=True
    )
    axes = axes.flatten()

    # outline colors and colormaps
    outline = {
        id1: ('red',  'Reds'),
        id2: ('blue', 'Blues')
    }

    # Pre-build the evaluation grid for KDE
    xi, yi = np.mgrid[minx:maxx:kde_grid_size*1j, miny:maxy:kde_grid_size*1j]
    coords = np.vstack([xi.ravel(), yi.ravel()])

    for ax, sl in zip(axes, slices):
        # Select slice data
        b = b3857.query("pair_id==@pair and slice==@sl")
        p = p3857.query("pair_id==@pair and slice==@sl")
        if b.empty:
            ax.set_visible(False)
            continue

        # Per-slice MCPs
        row1 = b[b["idcollar"] == id1]
        row2 = b[b["idcollar"] == id2]
        poly1 = row1.geometry.values[0] if not row1.empty else None
        poly2 = row2.geometry.values[0] if not row2.empty else None

        # dict for convenience
        polys = {id1: poly1, id2: poly2}

        # Set up axis
        ax.set_facecolor('#f0f0f0')
        ax.set_xlim(minx-1000, maxx+1000)
        ax.set_ylim(miny-1000, maxy+1000)
        ax.set_aspect('equal', adjustable='box')

        # Try basemap
        try:
            ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
        except Exception:
            pass

        # --- TWO KDEs: one per individual, clipped to its own MCP ---
        n1 = len(p[p["idcollar"] == id1])
        n2 = len(p[p["idcollar"] == id2])

        for this_id in [id1, id2]:
            pts = p[p["idcollar"] == this_id]

            if len(pts) < 5:
                continue  # need enough points for smooth KDE

            kde = gaussian_kde(
                np.vstack([pts.geometry.x.values, pts.geometry.y.values])
            )
            zi = kde(coords).reshape(xi.shape)

            poly = polys[this_id]
            if poly is not None and not poly.is_empty:
                mask = np.array(
                    [poly.contains(Point(x, y)) for x, y in zip(coords[0], coords[1])]
                ).reshape(xi.shape)
                zi = np.ma.masked_where(~mask, zi)

            cmap = outline[this_id][1]  # 'Reds' or 'Blues'
            # lower alpha so overlap is still readable
            ax.contourf(xi, yi, zi, levels=12, cmap=cmap, alpha=0.45, zorder=1)

        # Plot MCP outlines (red & blue)
        if poly1 is not None:
            row1.plot(ax=ax, facecolor="none", edgecolor=outline[id1][0],
                      linewidth=2, zorder=3)
        if poly2 is not None:
            row2.plot(ax=ax, facecolor="none", edgecolor=outline[id2][0],
                      linewidth=2, zorder=3)

        # Legend (counts)
        legend_handles = [
            Line2D([0], [0], color=outline[id1][0], lw=3, label=f"{label1} (n={n1})"),
            Line2D([0], [0], color=outline[id2][0], lw=3, label=f"{label2} (n={n2})"),
        ]
        ax.legend(handles=legend_handles, title="Counts", loc="upper right",
                  fontsize=9, title_fontsize=10, frameon=False)

        # 2 km scale bar (meters in EPSG:3857)
        x0 = minx + 0.05*(maxx - minx)
        y0 = miny + 0.05*(maxy - miny)
        x1 = x0 + 2_000  # 2 km
        ax.hlines(y=y0, xmin=x0, xmax=x1, colors="k", linewidth=2)
        ax.text((x0+x1)/2, y0 - 0.02*(maxy - miny), "2 km",
                ha="center", va="top", fontsize=10, color="k")

        # North arrow
        ax.annotate(
            '',
            xy=(0.95, 0.2), xycoords='axes fraction',
            xytext=(0.95, 0.05), textcoords='axes fraction',
            arrowprops=dict(facecolor='k', width=2, headwidth=8)
        )
        ax.text(0.95, 0.22, 'N', transform=ax.transAxes,
                ha='center', va='bottom', fontsize=12, fontweight='bold')

        ax.set_title(f"Partition {sl}", fontsize=12)
        ax.set_axis_off()

    # Hide unused axes
    for ax in axes[n_slices:]:
        ax.set_visible(False)

    fig.suptitle(f"Home Range & KDE for Pair {label1}-{label2}", fontsize=16)

    plt.savefig(f"../../figure/{pair}_Home_Range_KDE_only.jpg",
                dpi=500, bbox_inches='tight')
    plt.show()

## Figure 3: Heatmap with Index

In [17]:
def harmonize_time_bin_to_labels(
    s: pd.Series,
    bin_labels: list,
    time_bins: list
) -> pd.Categorical:
    """
    Map a time_bin series to your string labels robustly.
    - Normalizes dashes (EN dash → hyphen), trims spaces.
    - If strings already match labels (after normalization), keeps them.
    - Otherwise, expects numeric minutes and bins using `time_bins`.
    """
    s = pd.Series(s)

    # normalize text (dash & spaces)
    s_str = (
        s.astype(str)
         .str.replace("–", "-", regex=False)   # EN dash -> hyphen
         .str.replace("—", "-", regex=False)   # EM dash -> hyphen (just in case)
         .str.strip()
    )

    # also normalize the incoming label set
    norm_labels = [lbl.replace("–","-").replace("—","-").strip() for lbl in bin_labels]

    # if all already labels, return ordered categorical
    if s_str.isin(norm_labels).all():
        return pd.Categorical(s_str, categories=norm_labels, ordered=True)

    # otherwise treat as numeric minutes and cut into bins
    if time_bins is None:
        raise ValueError("Provide time_bins (edges, in minutes) to map numeric time_bin to labels.")
    mins = pd.to_numeric(s, errors='coerce')
    cats = pd.cut(mins, bins=time_bins, labels=norm_labels, include_lowest=True, right=True)
    return pd.Categorical(cats, categories=norm_labels, ordered=True)

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
from typing import Tuple, List, Optional


# Optional manual override if automatic PPA-key inference fails.
# Example after inspecting a pairs parquet:
#   PPA_SIDE1_KEY_COLS = ["idcollar_1", "start_time_1", "end_time_1"]
#   PPA_SIDE2_KEY_COLS = ["idcollar_2", "start_time_2", "end_time_2"]
PPA_SIDE1_KEY_COLS = None
PPA_SIDE2_KEY_COLS = None


def drop_exact_duplicate_rows_robust(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """
    Drop exact duplicate rows robustly, including object/geometry columns.

    This is only used to protect metric counts from accidental repeated parquet
    rows after file moving / bin-splitting repairs.
    """
    if df is None or df.empty:
        return df.copy(), 0

    key = df.copy()
    for c in key.columns:
        key[c] = key[c].map(lambda x: repr(x))

    dup_mask = key.duplicated(keep="first")
    return df.loc[~dup_mask].copy(), int(dup_mask.sum())


def _standardize_pair_slice_bin(df: pd.DataFrame, bin_labels: list, time_bins: list, id_pair=None) -> pd.DataFrame:
    """
    Standardize pair_id, slice, and time_bin for event/pair tables.
    """
    out = df.copy()

    if "slice" in out.columns:
        out["slice"] = pd.to_numeric(out["slice"], errors="coerce").astype("Int64")
    else:
        out["slice"] = pd.Series(pd.NA, index=out.index, dtype="Int64")

    if id_pair is not None:
        out["pair_id"] = _canonical_pair_id_from_ids(None, None, id_pair=id_pair)
    elif "pair_id" not in out.columns:
        if {"p1", "p2"}.issubset(out.columns):
            out["pair_id"] = [
                _canonical_pair_id_from_ids(a, b, id_pair=None)
                for a, b in zip(out["p1"], out["p2"])
            ]
        elif {"id1", "id2"}.issubset(out.columns):
            out["pair_id"] = [
                _canonical_pair_id_from_ids(a, b, id_pair=None)
                for a, b in zip(out["id1"], out["id2"])
            ]
        elif {"idcollar_1", "idcollar_2"}.issubset(out.columns):
            out["pair_id"] = [
                _canonical_pair_id_from_ids(a, b, id_pair=None)
                for a, b in zip(out["idcollar_1"], out["idcollar_2"])
            ]
        else:
            out["pair_id"] = "unknown_pair"

    out["pair_id"] = out["pair_id"].astype(str)

    if "time_bin" in out.columns:
        out["time_bin"] = harmonize_time_bin_to_labels(out["time_bin"], bin_labels, time_bins)
        out["time_bin"] = (
            out["time_bin"].astype(str)
            .str.replace("–", "-", regex=False)
            .str.replace("—", "-", regex=False)
            .str.strip()
        )
    else:
        out["time_bin"] = ""

    return out


def _norm_col_name(c: str) -> str:
    return str(c).lower().replace("-", "_").replace(" ", "_")


def _is_bookkeeping_or_output_col(c: str) -> bool:
    lc = _norm_col_name(c)
    bad_substrings = [
        "time_bin", "slice", "pair_id", "mc_round", "duration",
        "area", "overlap", "intersect", "geometry", "geom", "wkt",
        "distance", "dist", "delay", "difference", "diff",
        "classification", "state", "label", "frequency", "count",
    ]
    return any(x in lc for x in bad_substrings)


def _is_ppa_identity_candidate(c: str) -> bool:
    """
    Keep columns likely to identify a PPA/trajectory segment:
    animal id + start/end/time/index/segment identifiers.
    Avoid geometry/area/overlap columns because they can change by pair row
    and would over-count one PPA that intersects multiple PPAs.
    """
    lc = _norm_col_name(c)
    if _is_bookkeeping_or_output_col(c):
        # allow actual time/start/end columns despite containing "time"
        if not any(k in lc for k in ["start", "end", "timestamp", "datetime", "date"]):
            return False

    good = [
        "id", "collar", "animal", "track",
        "time", "date", "timestamp", "datetime", "start", "end",
        "idx", "index", "row", "segment", "seg", "ppa", "point", "fix",
    ]
    return any(k in lc for k in good)


def _side_of_column(c: str) -> Optional[int]:
    """
    Infer whether a column belongs to side 1 or side 2 of a PPA pair.
    Supports common conventions:
      *_1 / *_2, *1 / *2, *_x / *_y,
      id1/id2, time1/time2, start_time_1/start_time_2, p1/p2.
    """
    lc = _norm_col_name(c)

    # exact/common names
    side1_exact = {
        "p1", "id1", "id_1", "idcollar_1", "idcollar_x", "animal_1", "animal_x",
        "time1", "time_1", "time_x", "start_time_1", "end_time_1",
        "t1", "t_1", "idx1", "idx_1", "index1", "index_1",
        "segment1", "segment_1", "ppa1", "ppa_1"
    }
    side2_exact = {
        "p2", "id2", "id_2", "idcollar_2", "idcollar_y", "animal_2", "animal_y",
        "time2", "time_2", "time_y", "start_time_2", "end_time_2",
        "t2", "t_2", "idx2", "idx_2", "index2", "index_2",
        "segment2", "segment_2", "ppa2", "ppa_2"
    }
    if lc in side1_exact:
        return 1
    if lc in side2_exact:
        return 2

    # suffix conventions
    if re.search(r"(^|_)1($|_)", lc) or lc.endswith("_1") or lc.endswith("1"):
        return 1
    if re.search(r"(^|_)2($|_)", lc) or lc.endswith("_2") or lc.endswith("2"):
        return 2
    if lc.endswith("_x"):
        return 1
    if lc.endswith("_y"):
        return 2

    return None


def infer_ppa_side_key_columns(df: pd.DataFrame, verbose: bool = False) -> Tuple[List[str], List[str], str]:
    """
    Infer columns that identify the PPA/trajectory segment on each side
    of an intersecting PPA-pair row.

    If automatic inference is not enough, set global:
      PPA_SIDE1_KEY_COLS, PPA_SIDE2_KEY_COLS
    """
    global PPA_SIDE1_KEY_COLS, PPA_SIDE2_KEY_COLS

    if PPA_SIDE1_KEY_COLS is not None and PPA_SIDE2_KEY_COLS is not None:
        missing = [c for c in list(PPA_SIDE1_KEY_COLS) + list(PPA_SIDE2_KEY_COLS) if c not in df.columns]
        if missing:
            raise ValueError(f"Manual PPA key columns not found in pairs dataframe: {missing}")
        return list(PPA_SIDE1_KEY_COLS), list(PPA_SIDE2_KEY_COLS), "manual_override"

    side1, side2 = [], []
    for c in df.columns:
        if not _is_ppa_identity_candidate(c):
            continue
        side = _side_of_column(c)
        if side == 1:
            side1.append(c)
        elif side == 2:
            side2.append(c)

    side1 = sorted(set(side1), key=lambda x: list(df.columns).index(x))
    side2 = sorted(set(side2), key=lambda x: list(df.columns).index(x))

    # Need at least one identity/time/index column on each side.
    # Better if side-specific columns include more than only p1/p2/id.
    if verbose:
        print("Inferred PPA side1 cols:", side1)
        print("Inferred PPA side2 cols:", side2)

    if len(side1) == 0 or len(side2) == 0:
        return side1, side2, "failed_infer_ppa_columns"

    return side1, side2, "auto_inferred"


def _make_ppa_key(df: pd.DataFrame, cols: List[str], side_prefix: str) -> pd.Series:
    """
    Build a stable string key for one side's PPA.

    Prefix side1/side2 is intentional: all_ppa counts PPAs from both individuals,
    so the two individuals' PPAs should remain distinct even if timestamps match.
    """
    if not cols:
        return pd.Series(pd.NA, index=df.index, dtype="object")

    tmp = df[cols].copy()

    for c in tmp.columns:
        lc = _norm_col_name(c)
        if any(k in lc for k in ["time", "date", "timestamp", "datetime", "start", "end"]):
            parsed = pd.to_datetime(tmp[c], errors="coerce")
            if parsed.notna().any():
                tmp[c] = parsed.dt.strftime("%Y-%m-%d %H:%M:%S")
            else:
                tmp[c] = tmp[c].astype(str)
        else:
            tmp[c] = tmp[c].astype(str)

    return side_prefix + "|" + tmp.astype(str).agg("|".join, axis=1)


def count_unique_paired_ppas(pair_df: pd.DataFrame, verbose: bool = False) -> dict:
    """
    paired-PPA numerator.

    Definitions:
      pair_rows_raw = raw row count in the pairs parquet
      pair_rows     = exact-duplicate-safe row count
      paired_ppa    = number of UNIQUE PPAs, from both individuals, that
                      participate in at least one intersecting PPA pair
    """
    base = {
        "pair_rows_raw": 0,
        "pair_rows": 0,
        "paired_ppa": 0,
        "n_pair_exact_duplicates": 0,
        "side1_cols": "",
        "side2_cols": "",
        "count_method": "empty",
    }

    if pair_df is None or pair_df.empty:
        return base

    raw_n = int(len(pair_df))
    clean, n_dup = drop_exact_duplicate_rows_robust(pair_df)

    if clean.empty:
        base.update({
            "pair_rows_raw": raw_n,
            "pair_rows": 0,
            "paired_ppa": 0,
            "n_pair_exact_duplicates": n_dup,
            "count_method": "empty_after_dedup",
        })
        return base

    side1_cols, side2_cols, method = infer_ppa_side_key_columns(clean, verbose=verbose)

    if method == "failed_infer_ppa_columns":
        # Keep NaN visible so the audit flags the problem.
        return {
            "pair_rows_raw": raw_n,
            "pair_rows": int(len(clean)),
            "paired_ppa": np.nan,
            "n_pair_exact_duplicates": n_dup,
            "side1_cols": ",".join(side1_cols),
            "side2_cols": ",".join(side2_cols),
            "count_method": method,
        }

    key1 = _make_ppa_key(clean, side1_cols, "side1")
    key2 = _make_ppa_key(clean, side2_cols, "side2")

    paired_ppa = pd.concat([key1, key2], ignore_index=True).dropna().nunique()

    return {
        "pair_rows_raw": raw_n,
        "pair_rows": int(len(clean)),
        "paired_ppa": int(paired_ppa),
        "n_pair_exact_duplicates": n_dup,
        "side1_cols": ",".join(side1_cols),
        "side2_cols": ",".join(side2_cols),
        "count_method": method,
    }


def summarize_obs_pairs(
    df_obs_pairs: pd.DataFrame,
    bin_labels: list,
    time_bins: list,
    id_pair: Tuple[int, int] = None,
) -> pd.DataFrame:
    """
    Observed paired PPAs per (pair_id, slice, time_bin label).

    Metric definition:
      pair_rows_raw = raw row count in observed pairs parquet
      pair_rows     = exact-duplicate-safe row count in observed pairs parquet
      paired_ppa    = unique PPAs from both individuals that appear in at
                      least one pair row

    This guarantees paired_ppa <= all_ppa when all_ppa is the total number
    of PPAs from the two individuals in the partition.
    """
    cols = [
        "pair_id", "slice", "time_bin",
        "pair_rows_raw", "pair_rows", "paired_ppa",
        "n_pair_exact_duplicates", "side1_cols", "side2_cols", "count_method"
    ]

    if df_obs_pairs is None or df_obs_pairs.empty:
        return pd.DataFrame(columns=cols)

    df = _standardize_pair_slice_bin(df_obs_pairs, bin_labels, time_bins, id_pair=id_pair)
    df = df.dropna(subset=["slice"]).copy()
    df["slice"] = df["slice"].astype(int)

    rows = []
    for (pid, sl, tb), sub in df.groupby(["pair_id", "slice", "time_bin"], observed=True, dropna=False):
        counts = count_unique_paired_ppas(sub, verbose=False)
        counts.update({
            "pair_id": str(pid),
            "slice": int(sl),
            "time_bin": str(tb),
        })
        rows.append(counts)

    if not rows:
        return pd.DataFrame(columns=cols)

    out = pd.DataFrame(rows)
    return out[cols]

In [19]:
# =============================================================================
# PATCH: robust unique-PPA key inference for ORTEGA pair files
# =============================================================================
# Correct definition used below:
#   frequency  = number of rows in observed events parquet
#   pair_rows  = duplicate-safe number of rows in observed pairs parquet
#   paired_ppa = number of UNIQUE PPAs from both individuals that participate in
#                at least one intersecting PPA pair
#
# For ORTEGA pair files, a PPA is identified by: animal ID + segment start time + segment end time.

import re
import numpy as np
import pandas as pd
from typing import List, Tuple, Optional


def _norm_col_name(c: str) -> str:
    return str(c).lower().replace("-", "_").replace(" ", "_")


def _is_ppa_identity_candidate(c: str) -> bool:
    """
    Keep only columns that identify a PPA/trajectory segment.
    We intentionally exclude coordinates, speed, direction, geometry, and metrics,
    because those can vary by pair row and would over-count a single PPA.
    """
    lc = _norm_col_name(c)

    # Exclude non-identity columns first.
    bad_substrings = [
        "time_bin", "slice", "pair_id", "mc_round", "duration",
        "area", "overlap", "intersect", "geometry", "geom", "wkt",
        "distance", "dist", "delay", "difference", "diff",
        "classification", "state", "label", "frequency", "count",
        "speed", "direction", "bearing", "azimuth",
        "lat", "lon", "lng", "easting", "northing", "xcoord", "ycoord",
        "startlat", "startlon", "endlat", "endlon",
    ]
    if any(x in lc for x in bad_substrings):
        return False

    # ORTEGA segment identifiers and common alternatives.
    good_substrings = [
        "p1", "p2", "id", "collar", "animal", "track",
        "time", "date", "timestamp", "datetime", "start", "end",
        "idx", "index", "row", "segment", "seg", "ppa", "point", "fix",
    ]
    return any(k in lc for k in good_substrings)


def _side_of_column(c: str) -> Optional[int]:
    """
    Infer whether a column belongs to side 1 or side 2 of a PPA pair.
    Supports ORTEGA p1_/p2_ prefixes plus common suffix conventions.
    """
    lc = _norm_col_name(c)

    # ORTEGA pair-file convention: p1, p1_t_start, p1_t_end, ... / p2, p2_t_start, p2_t_end, ...
    if lc == "p1" or lc.startswith("p1_"):
        return 1
    if lc == "p2" or lc.startswith("p2_"):
        return 2

    side1_exact = {
        "id1", "id_1", "idcollar_1", "idcollar_x", "animal_1", "animal_x",
        "time1", "time_1", "time_x", "start_time_1", "end_time_1",
        "t1", "t_1", "idx1", "idx_1", "index1", "index_1",
        "segment1", "segment_1", "seg1", "seg_1", "ppa1", "ppa_1"
    }
    side2_exact = {
        "id2", "id_2", "idcollar_2", "idcollar_y", "animal_2", "animal_y",
        "time2", "time_2", "time_y", "start_time_2", "end_time_2",
        "t2", "t_2", "idx2", "idx_2", "index2", "index_2",
        "segment2", "segment_2", "seg2", "seg_2", "ppa2", "ppa_2"
    }
    if lc in side1_exact:
        return 1
    if lc in side2_exact:
        return 2

    if lc.endswith("_x"):
        return 1
    if lc.endswith("_y"):
        return 2
    if re.search(r"(^|_)1($|_)", lc) or lc.endswith("_1") or lc.endswith("1"):
        return 1
    if re.search(r"(^|_)2($|_)", lc) or lc.endswith("_2") or lc.endswith("2"):
        return 2

    return None


def infer_ppa_side_key_columns(df: pd.DataFrame, verbose: bool = False) -> Tuple[List[str], List[str], str]:
    """
    Infer columns that identify one PPA on each side of a PPA-pair row.

    Priority is given to ORTEGA's canonical pair-file columns:
      side 1: p1, p1_t_start, p1_t_end
      side 2: p2, p2_t_start, p2_t_end

    These identify a PPA as animal ID + segment start + segment end.
    """
    global PPA_SIDE1_KEY_COLS, PPA_SIDE2_KEY_COLS

    # Manual override, if the user sets it.
    if PPA_SIDE1_KEY_COLS is not None and PPA_SIDE2_KEY_COLS is not None:
        missing = [c for c in list(PPA_SIDE1_KEY_COLS) + list(PPA_SIDE2_KEY_COLS) if c not in df.columns]
        if missing:
            raise ValueError(f"Manual PPA key columns not found in pairs dataframe: {missing}")
        return list(PPA_SIDE1_KEY_COLS), list(PPA_SIDE2_KEY_COLS), "manual_override"

    cols = set(df.columns)

    # Best match for ORTEGA pair files.
    if {"p1", "p1_t_start", "p1_t_end", "p2", "p2_t_start", "p2_t_end"}.issubset(cols):
        side1 = ["p1", "p1_t_start", "p1_t_end"]
        side2 = ["p2", "p2_t_start", "p2_t_end"]
        if verbose:
            print("Using ORTEGA p1/p2 time-interval PPA keys:", side1, side2)
        return side1, side2, "ortega_p1p2_time_interval"

    # Alternative event-style naming, if it appears in pair files.
    if {"p1", "p1_start", "p1_end", "p2", "p2_start", "p2_end"}.issubset(cols):
        side1 = ["p1", "p1_start", "p1_end"]
        side2 = ["p2", "p2_start", "p2_end"]
        if verbose:
            print("Using p1/p2 start-end PPA keys:", side1, side2)
        return side1, side2, "p1p2_start_end"

    # General fallback.
    side1, side2 = [], []
    for c in df.columns:
        if not _is_ppa_identity_candidate(c):
            continue
        side = _side_of_column(c)
        if side == 1:
            side1.append(c)
        elif side == 2:
            side2.append(c)

    side1 = sorted(set(side1), key=lambda x: list(df.columns).index(x))
    side2 = sorted(set(side2), key=lambda x: list(df.columns).index(x))

    if verbose:
        print("Inferred PPA side1 cols:", side1)
        print("Inferred PPA side2 cols:", side2)

    if len(side1) == 0 or len(side2) == 0:
        return side1, side2, "failed_infer_ppa_columns"

    return side1, side2, "auto_inferred"


print("Loaded PATCH: ORTEGA p1/p2 time-interval columns will be used for unique paired-PPA counting.")

Loaded PATCH: ORTEGA p1/p2 time-interval columns will be used for unique paired-PPA counting.

In [20]:
def attach_ppa_to_gdf(
    gdf_merged: pd.DataFrame,
    df_obs_pairs: pd.DataFrame,
    bin_labels: list,
    time_bins: list,
    id_pair: Tuple[int, int] = None,
    df_obs_events: pd.DataFrame = None,
) -> pd.DataFrame:
    """
    Return a FULL grid (pair_id, slice, time_bin) with:
      frequency, pair_rows, paired_ppa, all_ppa, overlapped_area_km2, ppa_prop.

    Correct final metric definitions:
      frequency  = row count in observed events parquet
      pair_rows  = duplicate-safe row count in observed pairs parquet
      paired_ppa = number of UNIQUE PPAs from both individuals that participate
                   in at least one intersecting PPA pair
      all_ppa    = total number of PPAs from both individuals in the partition
      ppa_prop   = paired_ppa / all_ppa

    This means paired_ppa should never exceed all_ppa. If it does, the audit
    column paired_ppa_exceeds_all_ppa will flag the row.
    """
    base = gdf_merged.copy()
    base["pair_id"] = base["pair_id"].astype(str)
    base["slice"] = pd.to_numeric(base["slice"], errors="coerce").astype("Int64")
    base["time_bin"] = (
        base["time_bin"].astype(str)
        .str.replace("–", "-", regex=False)
        .str.replace("—", "-", regex=False)
        .str.strip()
    )

    if "n_events" not in base.columns:
        base["n_events"] = 0

    # Total opportunity per pair/slice from the home-range table.
    # n_points per individual gives GPS fixes; PPAs are consecutive-fix intervals,
    # so total PPAs from both individuals = sum(n_points) - 2.
    pts_pair_slice = (
        base[["pair_id", "slice", "idcollar", "n_points", "overlapped_area_km2"]]
        .drop_duplicates()
        .groupby(["pair_id", "slice"], as_index=False)
        .agg(
            total_points=("n_points", "sum"),
            overlapped_area_km2=("overlapped_area_km2", "first"),
        )
    )
    pts_pair_slice["all_ppa"] = (pts_pair_slice["total_points"] - 2).clip(lower=0)

    # Full grid of pair/slice/time_bin from gdf_merged.
    # n_events comes from integrate_event_counts() and is the observed event frequency.
    full_grid = (
        base[["pair_id", "slice", "time_bin", "n_events"]]
        .drop_duplicates()
        .rename(columns={"n_events": "frequency"})
        .merge(
            pts_pair_slice[["pair_id", "slice", "all_ppa", "overlapped_area_km2"]],
            on=["pair_id", "slice"],
            how="left",
        )
    )

    df_obs_summary = summarize_obs_pairs(
        df_obs_pairs=df_obs_pairs,
        bin_labels=bin_labels,
        time_bins=time_bins,
        id_pair=id_pair,
    )
    if not df_obs_summary.empty:
        df_obs_summary["pair_id"] = df_obs_summary["pair_id"].astype(str)
        df_obs_summary["slice"] = pd.to_numeric(df_obs_summary["slice"], errors="coerce").astype("Int64")
        df_obs_summary["time_bin"] = df_obs_summary["time_bin"].astype(str)

    out = full_grid.merge(
        df_obs_summary,
        on=["pair_id", "slice", "time_bin"],
        how="left",
    )

    # No matching pair rows means zero paired PPAs. But if pair_rows > 0 and
    # paired_ppa is NaN, automatic PPA-key inference failed and should remain visible.
    for c in ["frequency", "pair_rows_raw", "pair_rows", "n_pair_exact_duplicates", "all_ppa", "overlapped_area_km2"]:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce").fillna(0)

    out["frequency"] = out["frequency"].astype(int)
    out["pair_rows_raw"] = out["pair_rows_raw"].astype(int)
    out["pair_rows"] = out["pair_rows"].astype(int)
    out["n_pair_exact_duplicates"] = out["n_pair_exact_duplicates"].astype(int)

    # Fill paired_ppa = 0 only for rows with no pair rows.
    out["paired_ppa"] = pd.to_numeric(out["paired_ppa"], errors="coerce")
    no_pair_rows = out["pair_rows"].fillna(0).eq(0)
    out.loc[no_pair_rows, "paired_ppa"] = out.loc[no_pair_rows, "paired_ppa"].fillna(0)

    # Fill diagnostic strings
    out["count_method"] = out.get("count_method", pd.Series(index=out.index, dtype="object"))
    out.loc[no_pair_rows & out["count_method"].isna(), "count_method"] = "no_pair_rows"
    out["side1_cols"] = out.get("side1_cols", pd.Series(index=out.index, dtype="object")).fillna("")
    out["side2_cols"] = out.get("side2_cols", pd.Series(index=out.index, dtype="object")).fillna("")

    # Backward-compatible alias for older plotting/audit code.
    out["n_events"] = out["frequency"].astype(int)

    out["ppa_prop"] = np.where(
        out["all_ppa"] > 0,
        out["paired_ppa"] / out["all_ppa"],
        np.nan
    )

    out["paired_ppa_exceeds_all_ppa"] = (
        pd.to_numeric(out["paired_ppa"], errors="coerce") >
        pd.to_numeric(out["all_ppa"], errors="coerce")
    )

    return out

In [21]:
def compute_indices(
    df: pd.DataFrame,
    area_col: str = "overlapped_area_km2",
    prop_col: str = "ppa_prop",
    opportunity_col: str = "all_ppa",
    group_by_pair: bool = True,
) -> pd.DataFrame:
    """
    Recompute interaction metrics using the original visualization formula,
    with corrected paired_ppa inputs.

    D = ppa_prop / overlapped_area_km2
    D0 = mean D, either per pair or global
    I = (D - D0) / (D + D0)
    PC1 = z(log(ppa_prop + 1)) + z(log(overlapped_area_km2 + 1))
    PC1_norm = PC1 rescaled to [-1, 1]

    Important:
      paired_ppa must be the number of UNIQUE PPAs involved in interactions.
    """
    out = df.copy()
    eps = 1e-9

    numeric_cols = [
        area_col, prop_col, opportunity_col, "frequency", "n_events",
        "pair_rows_raw", "pair_rows", "paired_ppa", "n_pair_exact_duplicates"
    ]
    for c in numeric_cols:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")

    area = out[area_col].replace({0: np.nan})
    out["D"] = out[prop_col] / area
    out["D"] = out["D"].replace([np.inf, -np.inf], np.nan)

    if group_by_pair and "pair_id" in out.columns:
        out["D0"] = out.groupby("pair_id")["D"].transform("mean")
    else:
        out["D0"] = out["D"].mean()

    denom = out["D"] + out["D0"]
    out["I"] = np.where(denom > eps, (out["D"] - out["D0"]) / (denom + eps), np.nan)
    out["I"] = pd.to_numeric(out["I"], errors="coerce").clip(-1, 1)

    # Original PC1 formula from the old visualization:
    # association strength combines paired-PPA participation and overlap area.
    ln_n = np.log(pd.to_numeric(out[prop_col], errors="coerce") + 1.0)
    ln_a = np.log(pd.to_numeric(out[area_col], errors="coerce") + 1.0)

    z_n = (ln_n - ln_n.mean(skipna=True)) / (ln_n.std(ddof=0, skipna=True) + eps)
    z_a = (ln_a - ln_a.mean(skipna=True)) / (ln_a.std(ddof=0, skipna=True) + eps)
    out["PC1"] = (z_n + z_a).replace([np.inf, -np.inf], np.nan)

    pc1_min, pc1_max = out["PC1"].min(skipna=True), out["PC1"].max(skipna=True)
    if pd.notna(pc1_min) and pd.notna(pc1_max) and pc1_max > pc1_min:
        out["PC1_norm"] = 2 * (out["PC1"] - pc1_min) / (pc1_max - pc1_min) - 1
    else:
        out["PC1_norm"] = 0.0

    out["PC1_norm"] = pd.to_numeric(out["PC1_norm"], errors="coerce").clip(-1, 1)

    # Main diagnostic flags
    if "paired_ppa_exceeds_all_ppa" not in out.columns and {"paired_ppa", opportunity_col}.issubset(out.columns):
        out["paired_ppa_exceeds_all_ppa"] = out["paired_ppa"] > out[opportunity_col]

    out["metric_missing"] = out[["I", "PC1_norm"]].isna().any(axis=1)
    if "count_method" in out.columns:
        out.loc[out["count_method"].eq("failed_infer_ppa_columns"), "metric_missing"] = True
    if "paired_ppa_exceeds_all_ppa" in out.columns:
        out.loc[out["paired_ppa_exceeds_all_ppa"].fillna(False), "metric_missing"] = True

    return out

### Metric definitions

- `frequency` = row count in observed `events` parquet files.
- `paired_ppa` = the number of unique PPAs involved in observed `pairs` parquet files.
- `ppa_prop = paired_ppa / all_ppa` is a paired-PPA intensity.
- `PC1_norm = z(log(ppa_prop + 1)) + z(log(overlapped_area_km2 + 1))`, rescaled to [-1, 1].

In [22]:
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
from typing import List, Union, Tuple
from matplotlib.colors import LinearSegmentedColormap

def plot_interaction_heatmap(
    df: pd.DataFrame,
    bin_labels: List[str],
    pair_id: Union[str, Tuple[int,int]],
    slice_label: str = 'slice',
    prop_col: str = 'ppa_prop',
    opportunity_col: str = 'all_ppa',
    area_col: str = 'overlapped_area_km2',
    size_range: Tuple[int, int] = (20, 400)
):
    # normalize pair_id
    pid = f"{pair_id[0]}_{pair_id[1]}" if isinstance(pair_id, tuple) else pair_id
    dfp = df[df['pair_id'] == pid].copy()
    if dfp.empty:
        raise ValueError(f"No data for pair {pid}")

    # --- ensure we have the proportion column ---
    if prop_col not in dfp.columns:
        if {"paired_ppa", "all_ppa"}.issubset(dfp.columns):
            dfp[prop_col] = (dfp["paired_ppa"] + 0.5) / (dfp["all_ppa"] + 1.0)
        else:
            raise ValueError(
                f"Missing '{prop_col}' and also missing ['paired_ppa','all_ppa'] to derive it."
            )

    # --- compute I and PC1_norm if missing ---
    if ("I" not in dfp.columns) or ("PC1_norm" not in dfp.columns):
        dfp = compute_indices(
            dfp,
            area_col=area_col,
            prop_col=prop_col,
            opportunity_col="all_ppa",
            group_by_pair=True,
        )

    # map axes
    idx_map = {lbl: i for i, lbl in enumerate(bin_labels)}
    dfp['time_idx']  = dfp['time_bin'].map(idx_map)
    dfp['slice_idx'] = dfp[slice_label].astype(int)

    # scale sizes
    norm     = (dfp['PC1_norm'] + 1) / 2
    p = dfp['PC1_norm'].abs()
    cv = p.std() / (p.mean() + 1e-6)
    size_exp = 1 + cv
    norm_exp = norm ** size_exp
    min_s, max_s = size_range
    dfp['size'] = min_s + norm_exp * (max_s - min_s)

    # Define Green–Neutral–Purple colormap (avoidance → neutral → encounter)
    green_purple_cmap = LinearSegmentedColormap.from_list(
        "GreenPurple",
        ["#1b7939", "#ECF3F6", "#742881"]  # green (avoidance) → neutral → brown (encounter)
    )

    # Map IDs to labels
    id1, id2 = pair_id
    label1 = idcollar_mapping.get(str(id1), str(id1))
    label2 = idcollar_mapping.get(str(id2), str(id2))

    # 1) Create a figure whose axes take only 0–0.75 in x
    fig, ax = plt.subplots(
        figsize=(len(bin_labels)*1.0, dfp['slice_idx'].nunique()*0.6),
        constrained_layout=False,
        gridspec_kw={'left':0.1, 'right':0.75}
    )
    
    # 2) Draw the scatter on ax
    sc = ax.scatter(
        dfp['time_idx'], dfp['slice_idx'],
        s=dfp['size'], c=dfp['I'],
        cmap=green_purple_cmap, vmin=-1, vmax=1,
        edgecolor='k'
    )
    
    # 3) Axis formatting
    ax.set_xticks(list(idx_map.values()))
    ax.set_xticklabels(bin_labels, rotation=45, ha='right')
    ax.set_yticks(sorted(dfp['slice_idx'].unique()))
    ax.set_yticklabels(sorted(dfp['slice_idx'].unique()))
    ax.set_xlabel('Time Bin')
    ax.set_ylabel('Partition')
    ax.set_ylim(0.5, dfp['slice_idx'].max()+0.5)
    ax.set_title(f'Interaction Heatmap for Pair {label1}-{label2}', fontsize=16)
    
    # 4) Put the colorbar in the right margin
    cbar_ax = fig.add_axes([0.78, 0.55, 0.02, 0.35])  # [left, bottom, width, height]
    cbar = fig.colorbar(sc, cax=cbar_ax, orientation='vertical')
    # cbar.set_label('I (Normalized \n Interaction Density)', fontsize=9)
    cbar.set_ticks([-1, 1])
    cbar.set_ticklabels(['Avoidance', 'Colocation'])
    cbar.ax.tick_params(labelsize=9)
    cbar.outline.set_linewidth(0.6)
    
    # 5) Build dummy artists for the two legends
    # encounter_color = green_brown_cmap(1.0)  # Brown (encounter)
    # avoidance_color = green_brown_cmap(0.0)  # Green (avoidance)
    # neutral_color   = green_brown_cmap(0.5)  # Neutral

    # color_elements = [
    #     Line2D([0],[0], marker='o', color='w', 
    #            markerfacecolor=encounter_color, markersize=10, label='Encounter'),
    #     Line2D([0],[0], marker='o', color='w', 
    #            markerfacecolor=avoidance_color, markersize=10, label='Avoidance'),
    #     Line2D([0],[0], marker='o', color='w', 
    #            markerfacecolor=neutral_color, markersize=10, label='Neutral')
    # ]
    size_elements = [
        Line2D([0],[0], marker='o', color='white', linestyle='-', markeredgecolor='k',
               markersize=np.sqrt(size_range[0]), label='Weak (Low–Low)'),
        Line2D([0],[0], marker='o', color='white', linestyle='-', markeredgecolor='k',
               markersize=np.sqrt(size_range[1]), label='Strong (High–High)')
    ]
    
    # # 6) Place the color‐type legend
    # fig.legend(
    #     handles=color_elements,
    #     title="Interaction Type",
    #     loc='upper right',
    #     bbox_to_anchor=(0.9, 0.45),
    #     frameon=False
    # )
    
    # 7) Place the size‐strength legend
    fig.legend(
        handles=size_elements,
        title="Association Strength",
        loc='upper right',
        bbox_to_anchor=(1.03, 0.45),
        frameon=False
    )
    
    plt.savefig(f"../../figure/{pair_id[0]}_{pair_id[1]}_Interaction_Heatmap.jpg", dpi=500, bbox_inches='tight')
    plt.show()

## Figure 4: Home Range & Heatmap

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import contextily as ctx
from shapely.geometry import Point
from scipy.stats import gaussian_kde
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
from matplotlib.lines import Line2D
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

# ---- pretty ID helper (uses your mapping) ----
def _nice_label(animal_id: int) -> str:
    return idcollar_mapping.get(str(animal_id), str(animal_id))

# ---- palette + circle sizing ----
def _green_purple_cmap():
    return LinearSegmentedColormap.from_list("GreenPurple", ["#1b7939", "#ECF3F6", "#742881"])

def _circle_sizes(pc1_norm: pd.Series, size_range=(50, 260)) -> np.ndarray:
    # map PC1_norm [-1,1] -> [0,1] -> size range
    v = (pd.Series(pc1_norm).fillna(0).clip(-1,1) + 1.0) / 2.0
    return size_range[0] + v.values * (size_range[1] - size_range[0])


def standardize_metric_table_for_plot(gdf_idx: pd.DataFrame) -> pd.DataFrame:
    out = gdf_idx.copy()
    if out.empty:
        return out
    out["pair_id"] = out["pair_id"].astype(str)
    out["slice"] = pd.to_numeric(out["slice"], errors="coerce").astype("Int64")
    out["time_bin"] = (
        out["time_bin"].astype(str)
        .str.replace("–", "-", regex=False)
        .str.replace("—", "-", regex=False)
        .str.strip()
    )
    for c in ["I", "PC1", "PC1_norm", "D", "D0", "ppa_prop", "all_ppa", "frequency", "n_events", "pair_rows_raw", "pair_rows", "paired_ppa", "n_pair_exact_duplicates", "overlapped_area_km2", "paired_ppa_exceeds_all_ppa", "count_method", "side1_cols", "side2_cols"]:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


def _slice_bin_row(gdf_idx: pd.DataFrame, pair: str, sl: int, bin_labels: list) -> pd.DataFrame:
    """Return exactly one row per bin for a pair/slice, with explicit missing values."""
    g = standardize_metric_table_for_plot(gdf_idx)
    pair = str(pair)
    sl = int(sl)
    base = pd.DataFrame({"pair_id": pair, "slice": sl, "time_bin": bin_labels})
    if g.empty:
        base["I"] = np.nan
        base["PC1_norm"] = np.nan
        return base

    d = g[(g["pair_id"] == pair) & (g["slice"].astype("Int64") == sl)].copy()
    keep = ["pair_id", "slice", "time_bin"] + [c for c in ["I", "PC1", "PC1_norm", "D", "D0", "ppa_prop", "all_ppa", "frequency", "n_events", "pair_rows_raw", "pair_rows", "paired_ppa", "n_pair_exact_duplicates", "overlapped_area_km2", "paired_ppa_exceeds_all_ppa", "count_method", "side1_cols", "side2_cols"] if c in d.columns]
    d = d[keep].drop_duplicates(["pair_id", "slice", "time_bin"])
    return base.merge(d, on=["pair_id", "slice", "time_bin"], how="left")


def audit_circle_metrics(gdf_idx: pd.DataFrame, id_pair, bin_labels: list, expected_slices=None) -> pd.DataFrame:
    """Diagnostic table for the circle panel before plotting."""
    pair = f"{id_pair[0]}_{id_pair[1]}"
    g = standardize_metric_table_for_plot(gdf_idx)
    if expected_slices is None:
        expected_slices = sorted(g.loc[g["pair_id"] == pair, "slice"].dropna().astype(int).unique()) if not g.empty else []
    rows = []
    for sl in expected_slices:
        row_df = _slice_bin_row(g, pair, int(sl), bin_labels)
        for _, r in row_df.iterrows():
            rows.append({
                "pair_id": pair,
                "slice": int(sl),
                "time_bin": r["time_bin"],
                "I": r.get("I", np.nan),
                "PC1_norm": r.get("PC1_norm", np.nan),
                "frequency": r.get("frequency", r.get("n_events", np.nan)),
                "pair_rows_raw": r.get("pair_rows_raw", np.nan),
                "pair_rows": r.get("pair_rows", np.nan),
                "paired_ppa": r.get("paired_ppa", np.nan),
                "n_pair_exact_duplicates": r.get("n_pair_exact_duplicates", np.nan),
                "all_ppa": r.get("all_ppa", np.nan),
                "ppa_prop": r.get("ppa_prop", np.nan),
                "D": r.get("D", np.nan),
                "D0": r.get("D0", np.nan),
                "PC1": r.get("PC1", np.nan),
                "overlapped_area_km2": r.get("overlapped_area_km2", np.nan),
                "paired_ppa_exceeds_all_ppa": bool(r.get("paired_ppa_exceeds_all_ppa", False)) if pd.notna(r.get("paired_ppa_exceeds_all_ppa", False)) else False,
                "count_method": r.get("count_method", ""),
                "side1_cols": r.get("side1_cols", ""),
                "side2_cols": r.get("side2_cols", ""),
                "metric_missing": (
                    pd.isna(r.get("I", np.nan))
                    or pd.isna(r.get("PC1_norm", np.nan))
                    or bool(r.get("paired_ppa_exceeds_all_ppa", False))
                    or str(r.get("count_method", "")) == "failed_infer_ppa_columns"
                ),
            })
    return pd.DataFrame(rows)

In [24]:
import contextily as ctx

def add_basemap_safely(ax, gdf, source=None, zoom=11, alpha=0.55):
    """
    Add a basemap to an axis while preserving the current UTM extent.
    Works for UTM geometries such as EPSG:32647.
    """
    if source is None:
        source = ctx.providers.CartoDB.PositronNoLabels
        # Alternative:
        # source = ctx.providers.Esri.WorldImagery

    if gdf is None or gdf.empty:
        return

    crs = gdf.crs
    if crs is None:
        crs = "EPSG:32647"

    # Save current extent after polygons/points are plotted
    xlim = ax.get_xlim()
    ylim = ax.get_ylim()

    try:
        ctx.add_basemap(
            ax,
            crs=crs,
            source=source,
            zoom=zoom,
            alpha=alpha,
            attribution=False
        )

        # Restore original UTM extent
        ax.set_xlim(xlim)
        ax.set_ylim(ylim)

    except Exception as e:
        print(f"Basemap skipped: {repr(e)}")

In [25]:
def clamp_ymin_zero(ax):
    ymin, ymax = ax.get_ylim()
    if ymin < 0:
        if ymax <= 0:
            ymax = 1
        ax.set_ylim(0, ymax)

In [26]:
def plot_slices_hr_kde_grid_split(
    boundary_gdf: gpd.GeoDataFrame,
    point_gdf: gpd.GeoDataFrame,
    gdf_idx: pd.DataFrame,             # needs: pair_id, slice, time_bin, I, PC1_norm
    id_pair: Tuple[int,int],
    bin_labels: list,
    padding_frac: float = 0.05,        # padding around global map extent
    kde_grid_size: int = 100,
    circle_size_range=(50, 260),
    circle_band_height=0.20,           # ↑ more vertical room for circles
    circle_inner_pad: float = 0.04,    # pad inside the union span (fraction of that span)
    fig_scale=(5.2, 5.0),              # per-column, per-row sizing (width, height)
    show_size_legend=True,
    show_colorbar=True,
    save_path=None,
    show: bool = False
):
    """
    Makes a grid. For each partition tile we create two stacked sub-axes:
      (top)  circle strip with time-bin labels, aligned to the MCP union width
      (bottom) home-range + KDE map (now: separate KDEs for each animal)
    """
    id1, id2 = id_pair
    label1, label2 = _nice_label(id1), _nice_label(id2)
    pair = f"{id1}_{id2}"

    # color + colormap per individual
    outline = {
        id1: ("red",  "Reds"),
        id2: ("blue", "Blues"),
    }

    # ------- project / extent -------
    b3857 = boundary_gdf.to_crs(epsg=3857)
    p3857 = point_gdf.to_crs(epsg=3857)

    all_polys = b3857.query("pair_id==@pair")['geometry']
    if all_polys.empty:
        raise ValueError(f"No MCP data for pair {pair}")
    minx, miny, maxx, maxy = all_polys.unary_union.bounds
    pad_x = (maxx - minx) * padding_frac
    pad_y = (maxy - miny) * padding_frac
    # global map limits (same as before)
    xlim0, xlim1 = (minx - pad_x - 1000, maxx + pad_x + 1000)
    ylim0, ylim1 = (miny - pad_y - 1000, maxy + pad_y + 1000)

    slices = sorted(b3857.query("pair_id==@pair")['slice'].unique())
    if not slices:
        raise ValueError(f"No data for pair {pair}")
    n_slices = len(slices)

    # grid geometry (same logic as before)
    if n_slices < 4:   n_cols = n_slices
    elif n_slices <= 16:   n_cols = 4
    elif n_slices <= 25: n_cols = 5
    else:                n_cols = 6
    n_rows = int(np.ceil(n_slices / n_cols))

    # --- figure and outer GridSpec ---
    fig_w = fig_scale[0] * n_cols + 1.2
    fig_h = fig_scale[1] * n_rows * (1 + 0.10)  # a bit taller to accommodate circle bands
    fig = plt.figure(figsize=(fig_w, fig_h))
    gs_outer = GridSpec(nrows=n_rows, ncols=n_cols, figure=fig,
                        left=0.01, right=0.86, top=0.98, bottom=0.02,
                        wspace=0.02, hspace=0.2)

    # KDE grid (global, reused for all panels)
    xi, yi = np.mgrid[xlim0:xlim1:kde_grid_size*1j, ylim0:ylim1:kde_grid_size*1j]
    coords = np.vstack([xi.ravel(), yi.ravel()])

    # aesthetics for circles
    cmap = _green_purple_cmap()
    normI = Normalize(-1, 1)

    # --- loop tiles ---
    for idx, sl in enumerate(slices):
        r = idx // n_cols
        c = idx % n_cols

        # make a 2-row subgrid inside this tile: [circle row, map row]
        gs_tile = GridSpecFromSubplotSpec(
            2, 1, subplot_spec=gs_outer[r, c],
            height_ratios=[circle_band_height, 1 - circle_band_height],
            hspace=0.03
        )

        # ----- BOTTOM: map -----
        axM = fig.add_subplot(gs_tile[1, 0])
        b = b3857.query("pair_id==@pair and slice==@sl")
        p = p3857.query("pair_id==@pair and slice==@sl")

        if b.empty:
            axM.set_visible(False)
        else:
            row1 = b[b["idcollar"] == id1]
            row2 = b[b["idcollar"] == id2]
            poly1 = row1.geometry.values[0] if not row1.empty else None
            poly2 = row2.geometry.values[0] if not row2.empty else None

            # union still used later for circle alignment
            if   poly1 is not None and poly2 is not None: union_poly = poly1.union(poly2)
            elif poly1 is not None:                       union_poly = poly1
            elif poly2 is not None:                       union_poly = poly2
            else:                                         union_poly = None

            axM.set_facecolor("#f0f0f0")
            axM.set_xlim(xlim0, xlim1)
            axM.set_ylim(ylim0, ylim1)
            axM.set_aspect("equal", adjustable="box")
            
            # ---- Add basemap here, before KDE and polygons ----
            try:
                ctx.add_basemap(
                    axM,
                    source=ctx.providers.CartoDB.Positron,
                    crs=b3857.crs,              # b3857 is already EPSG:3857
                    zoom=11,
                    attribution=False,
                    reset_extent=False,
                    zorder=0
                )
            
                # restore extent after adding basemap
                axM.set_xlim(xlim0, xlim1)
                axM.set_ylim(ylim0, ylim1)
            
            except Exception as e:
                print(f"[Partition {sl}] Basemap skipped:", repr(e))

            # --- NEW: separate KDE per animal, clipped to its own MCP ---
            n1 = len(p[p["idcollar"] == id1])
            n2 = len(p[p["idcollar"] == id2])

            polys = {id1: poly1, id2: poly2}
            for this_id in [id1, id2]:
                pts = p[p["idcollar"] == this_id]
                if len(pts) < 5:
                    continue  # not enough points for smooth KDE

                kde = gaussian_kde(
                    np.vstack([pts.geometry.x.values, pts.geometry.y.values])
                )
                zi = kde(coords).reshape(xi.shape)

                poly = polys[this_id]
                if poly is not None and not poly.is_empty:
                    mask = np.array(
                        [poly.contains(Point(x, y)) for x, y in zip(coords[0], coords[1])]
                    ).reshape(xi.shape)
                    zi = np.ma.masked_where(~mask, zi)

                cmap_kde = outline[this_id][1]  # 'Reds' or 'Blues'
                axM.contourf(
                    xi, yi, zi, levels=12,
                    cmap=cmap_kde, alpha=0.45, zorder=1
                )

            # outlines + legend with pretty IDs
            if poly1 is not None:
                row1.plot(
                    ax=axM, facecolor="none",
                    edgecolor=outline[id1][0], linewidth=2, zorder=3
                )
            if poly2 is not None:
                row2.plot(
                    ax=axM, facecolor="none",
                    edgecolor=outline[id2][0], linewidth=2, zorder=3
                )

            axM.legend(
                handles=[
                    Line2D([0],[0], color=outline[id1][0], lw=3, label=f"{label1} (n={n1})"),
                    Line2D([0],[0], color=outline[id2][0], lw=3, label=f"{label2} (n={n2})"),
                ],
                title="Counts", loc="upper right",
                fontsize=12, title_fontsize=13, frameon=False
            )

            # 2 km scale + north
            x0 = xlim0 + 0.05*(xlim1 - xlim0)
            y0 = ylim0 + 0.05*(ylim1 - ylim0)
            x1 = x0 + 2_000
            axM.hlines(
                y=y0 + 0.1*(ylim1 - ylim0),
                xmin=x0, xmax=x1,
                colors="k", linewidth=2
            )
            axM.text(
                (x0+x1)/2, y0 + 0.14*(ylim1 - ylim0), "2 km",
                ha="center", va="top", fontsize=10, color="k"
            )
            axM.annotate(
                '', xy=(0.95,0.2), xycoords='axes fraction',
                xytext=(0.95,0.05), textcoords='axes fraction',
                arrowprops=dict(facecolor='k', width=2, headwidth=8)
            )
            axM.text(
                0.95, 0.22, 'N', transform=axM.transAxes,
                ha='center', va='bottom', fontsize=12,
                fontweight='bold'
            )
            axM.set_axis_off()

        # ----- TOP: circles (fixed equal spacing to avoid label overlap) -----
        axC = fig.add_subplot(gs_tile[0, 0])
        axC.set_xlim(0, 1)
        axC.set_ylim(0, 1)
        axC.set_xticks([])
        axC.set_yticks([])
        for sp in axC.spines.values():
            sp.set_visible(False)
        
        # Fixed positions for all bins, regardless of home-range span
        left_pad = 0.12
        right_pad = 0.88
        xs = np.linspace(left_pad, right_pad, len(bin_labels))
        ys = np.full(len(bin_labels), 0.58)
        
        row_df = _slice_bin_row(gdf_idx, pair, sl, bin_labels)
        sizes  = _circle_sizes(row_df["PC1_norm"], size_range=circle_size_range)
        colors = [cmap(normI(v)) if pd.notna(v) else (0, 0, 0, 0) for v in row_df["I"]]
        
        # # Optional: draw faint guide line or slots for visual alignment
        # for x in xs:
        #     axC.plot([x, x], [0.24, 0.82], color="lightgray", lw=0.4, alpha=0.5, zorder=0)
        
        axC.scatter(
            xs, ys,
            s=sizes,
            c=colors,
            edgecolors="k",
            linewidths=0.6,
            zorder=2
        )
        
        # Put labels at a fixed y so they never collide with circles
        for x, lbl in zip(xs, bin_labels):
            axC.text(
                x, 0.12, lbl,
                ha="center", va="top",
                fontsize=8,
                linespacing=0.9
            )
        
        axC.text(
            0.01, 0.94, f"Partition {sl}",
            ha="left", va="top",
            fontsize=12,
            transform=axC.transAxes,
            zorder=5
        )

    # ---- global legends/top matter ----
    if show_colorbar:
        cb_ax = fig.add_axes([0.90, 0.80, 0.012, 0.13])
        sm = plt.cm.ScalarMappable(cmap=cmap, norm=normI); sm.set_array([])
        cbar = plt.colorbar(sm, cax=cb_ax, orientation='vertical')
        cbar.set_ticks([-1, 1]); cbar.set_ticklabels(['Avoidance', 'Colocation'])
        cbar.ax.tick_params(labelsize=12); cbar.outline.set_linewidth(0.6)

    if show_size_legend:
        lg_ax = fig.add_axes([0.89, 0.65, 0.09, 0.08]); lg_ax.axis("off")
        s_min, s_max = circle_size_range
        handles = [
            Line2D([0],[0], marker='o', color='white', markeredgecolor='k',
                   markersize=np.sqrt(s_min), label='Weak'),
            Line2D([0],[0], marker='o', color='white', markeredgecolor='k',
                   markersize=np.sqrt(s_max), label='Strong')
        ]
        lg_ax.legend(handles=handles, title="Association strength", ncol=1,
                     loc="center", frameon=False, fontsize=12, title_fontsize=13)
    fig.canvas.draw()                
    if save_path:
        save_path = Path(save_path)
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=500, bbox_inches="tight")
    else:
        out_path = Path(f"../../figure/{id_pair[0]}_{id_pair[1]}_Home_Range_KDE.jpg")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out_path, dpi=500, bbox_inches="tight")

    if show:
        plt.show()
    else:
        plt.close(fig)
    return fig

## HPC supplementary visualization runner

This section adapts the notebook to the GRIT HPC output structure and saves figures directly under each pair folder and `supplementary_figures_all_dyads`.

In [ ]:
# =============================================================================
# HPC visualization settings
# Run this section after the plotting/helper function cells above.
# =============================================================================
import os
import json
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed
import multiprocessing as mp
from tqdm.auto import tqdm

# Keep notebook output clean and save figures directly to files
plt.ioff()

PROJECT_ROOT = Path("PROJECT_PATH")
DATA_DIR = PROJECT_ROOT / "data"
SIM_ROOT = PROJECT_ROOT / "simulated_trajectory"

TRACKING_FILE = DATA_DIR / "tiger_leopard_env_tg.csv"
ADJUSTED_DIR = DATA_DIR

MAIN_ANALYSIS_NAME = "CRW_slice_RT_WIN1000_MC0001_1000"
MAIN_RUN_ROOT = SIM_ROOT / MAIN_ANALYSIS_NAME

# All supplementary figures will also be collected here
SUPP_FIG_ROOT = SIM_ROOT / "supplementary_figures_all_dyads"
SUPP_FIG_ROOT.mkdir(parents=True, exist_ok=True)

WINDOW_HOURS = 1000
MC_START = 1
MC_END = 1000
MAX_MC_FOR_FIGURES = 1000

# Use the same bins/labels as the null model runs
bin_labels = ["0-1h", "1h-1d", "1-2d", "2-4d", "4-8d", "8-16d", "16-21d"]
time_bins  = [0, 60, 1440, 2880, 5760, 11520, 23040, 30240]

# Use your paper-style animal labels
idcollar_mapping = {
    '131343': 'FT1',
    '229011': 'FT2',
    '229041': 'FT3',
    '229012': 'MT1',
    '229022': 'MT2',
    '229032': 'MT3',
    '31899': 'FL',
    '31898': 'ML1',
    '37821': 'ML2',
    '37822': 'ML3',
    '37823': 'ML4'
}

# Main dyads
ALL_MAIN_ID_PAIRS = [
    (229041, 31898), (229041, 31899), (131343, 31898), (131343, 31899), 
    (131343, 37822), (229011, 31898), (229012, 31898), (229012, 37821), 
    (229012, 37823), (229022, 31898), (229022, 31899), (229022, 37822), 
    (229022, 37823), (229032, 31898), (229032, 37822), (229032, 37823),
]

# For batch plotting. You can reduce this if memory becomes high.
N_WORKERS = min(15, int(os.environ.get("SLURM_CPUS_PER_TASK", "15")))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("MAIN_RUN_ROOT:", MAIN_RUN_ROOT)
print("SUPP_FIG_ROOT:", SUPP_FIG_ROOT)
print("N_WORKERS:", N_WORKERS)

In [28]:
# =============================================================================
# HPC-aware loading, saving, and pair-level visualization wrappers
# =============================================================================

def pair_label(id_pair):
    """Paper-style pair label, e.g., FT2-ML1. Falls back to raw IDs."""
    id1, id2 = id_pair
    return f"{idcollar_mapping.get(str(id1), str(id1))}-{idcollar_mapping.get(str(id2), str(id2))}"


def pair_id_string(id_pair):
    return f"{id_pair[0]}_{id_pair[1]}"


def pair_dir_hpc(id_pair, analysis_name=MAIN_ANALYSIS_NAME):
    return SIM_ROOT / analysis_name / f"by_slice_{id_pair[0]}_{id_pair[1]}_reverse_time"


def pair_vis_dir_hpc(id_pair, analysis_name=MAIN_ANALYSIS_NAME):
    pdir = pair_dir_hpc(id_pair, analysis_name=analysis_name)
    out = pdir / "visualization_outputs"
    out.mkdir(parents=True, exist_ok=True)

    # Also make a collection folder with the paper-style label
    collect = SUPP_FIG_ROOT / pair_label(id_pair)
    collect.mkdir(parents=True, exist_ok=True)
    return out, collect


def _empty_event_df():
    return pd.DataFrame(columns=["slice", "time_bin", "MC_round", "duration", "difference", "p1", "p2"])


def _empty_pairs_df():
    return pd.DataFrame(columns=["slice", "time_bin", "MC_round", "p1", "p2"])


def _standardize_loaded_results(results):
    """Guarantee expected columns exist even when a pair has few/no events."""
    for k in ["sim_events", "obs_events"]:
        if k not in results or results[k] is None or results[k].empty:
            results[k] = _empty_event_df()
        else:
            for col in _empty_event_df().columns:
                if col not in results[k].columns:
                    results[k][col] = np.nan

    for k in ["sim_pairs", "obs_pairs"]:
        if k not in results or results[k] is None or results[k].empty:
            results[k] = _empty_pairs_df()
        else:
            for col in _empty_pairs_df().columns:
                if col not in results[k].columns:
                    results[k][col] = np.nan

    for k in results:
        if "slice" in results[k].columns:
            results[k]["slice"] = pd.to_numeric(results[k]["slice"], errors="coerce").astype("Int64")
        if "time_bin" in results[k].columns:
            results[k]["time_bin"] = (
                results[k]["time_bin"].astype(str)
                .str.replace("–", "-", regex=False)
                .str.replace("—", "-", regex=False)
                .str.strip()
            )
    return results


def summarize_interaction_results_hpc(
    id_pair,
    analysis_name=MAIN_ANALYSIS_NAME,
    max_mc=MAX_MC_FOR_FIGURES,
    write_out=True,
    verbose=True,
):
    """
    HPC wrapper around summarize_interaction_results().
    Works with the new nested structure:
      .../by_slice_ID1_ID2_reverse_time/sliceXXX/MC0001_1000/interactions/*.parquet
    """
    pdir = pair_dir_hpc(id_pair, analysis_name=analysis_name)
    if not pdir.exists():
        raise FileNotFoundError(f"Pair folder not found: {pdir}")

    results = summarize_interaction_results(
        id_pair=id_pair,
        base_dir=pdir,
        bin_labels=bin_labels,
        summary_folder="summary_hpc",
        max_mc=max_mc,
        write_out=write_out,
        verbose=verbose,
    )
    return _standardize_loaded_results(results)


def load_status_table():
    status_csv = SIM_ROOT / "run_status_pair_level_v3.csv"
    if not status_csv.exists():
        print(f"Status table not found: {status_csv}. Using ALL_MAIN_ID_PAIRS.")
        return None
    return pd.read_csv(status_csv)


def completed_pairs_from_status(status_df=None, analysis_name=MAIN_ANALYSIS_NAME):
    """
    Return pairs marked ALL_VALID_DONE in run_status_pair_level_v3.csv.
    Keeps skipped-empty slices as valid exclusions.
    """
    if status_df is None:
        status_df = load_status_table()
    if status_df is None:
        return ALL_MAIN_ID_PAIRS

    sub = status_df[
        (status_df["analysis"] == analysis_name) &
        (status_df["overall_status"].isin(["ALL_VALID_DONE", "ALL_SKIPPED_EMPTY_DATA"]))
    ].copy()

    pairs = []
    for p in sub["pair"].dropna().unique():
        a, b = p.split("_")
        pairs.append((int(a), int(b)))
    return pairs


def copy_to_collection(src_path, collect_dir):
    """Copy one figure to the global supplementary collection folder."""
    import shutil
    src_path = Path(src_path)
    collect_dir = Path(collect_dir)
    collect_dir.mkdir(parents=True, exist_ok=True)
    dst = collect_dir / src_path.name
    if src_path.exists():
        shutil.copy2(src_path, dst)
    return dst


def _safe_to_csv(df, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    # Drop geometry if present because CSV cannot store it cleanly
    d = df.copy()
    if "geometry" in d.columns:
        d["geometry_wkt"] = d["geometry"].astype(str)
        d = d.drop(columns=["geometry"])
    d.to_csv(path, index=False)

In [29]:
def filter_slices(df, slices_keep):
    if df is None or df.empty or "slice" not in df.columns:
        return df
    out = df.copy()
    out["slice"] = pd.to_numeric(out["slice"], errors="coerce")
    return out[out["slice"].isin(slices_keep)].copy()

In [30]:
def make_visualizations_for_pair_hpc(
    id_pair,
    analysis_name=MAIN_ANALYSIS_NAME,
    max_mc=MAX_MC_FOR_FIGURES,
    force=False,
    verbose=False,
    max_partition=None,
):
    """
    Generate two supplementary figures for one dyad:
      Figure 1: null-model three-panel figure
      Figure 4: home range + KDE + interaction-index circles
    Saves figures and intermediate summary tables to the pair output folder and global collection folder.
    """
    id_pair = tuple(id_pair)
    id1, id2 = id_pair
    raw_pair = pair_id_string(id_pair)
    label = pair_label(id_pair)

    pdir = pair_dir_hpc(id_pair, analysis_name=analysis_name)
    out_dir, collect_dir = pair_vis_dir_hpc(id_pair, analysis_name=analysis_name)
    suffix = "_first4part" if max_partition is not None else ""

    fig1_path = out_dir / f"{label}_{raw_pair}_Fig1_null_model_three_panel{suffix}.jpg"
    fig4_path = out_dir / f"{label}_{raw_pair}_Fig4_home_range_interaction_grid{suffix}.jpg"

    if (not force) and fig1_path.exists() and fig4_path.exists():
        return {
            "pair": raw_pair,
            "label": label,
            "status": "skipped_existing",
            "fig1": str(fig1_path),
            "fig4": str(fig4_path),
        }

    try:
        # ---------------------------------------------------------
        # Load simulated and observed interaction outputs
        # ---------------------------------------------------------
        results = summarize_interaction_results_hpc(
            id_pair=id_pair,
            analysis_name=analysis_name,
            max_mc=max_mc,
            write_out=True,
            verbose=verbose,
        )

        df_sim_events = add_following_state(results["sim_events"], id_pair=id_pair)
        df_sim_pairs  = results["sim_pairs"]
        df_obs_events = add_following_state(results["obs_events"], id_pair=id_pair)
        df_obs_pairs  = results["obs_pairs"]

        # -------------------------------------------------
        # Restrict to first N partitions if requested
        # -------------------------------------------------
        slices_all = sorted(pd.to_numeric(df_sim_events["slice"], errors="coerce").dropna().unique())
        
        if max_partition is not None:
            slices_keep = slices_all[:max_partition]
        else:
            slices_keep = slices_all
        
        df_sim_events = filter_slices(df_sim_events, slices_keep)
        df_sim_pairs  = filter_slices(df_sim_pairs, slices_keep)
        df_obs_events = filter_slices(df_obs_events, slices_keep)
        df_obs_pairs  = filter_slices(df_obs_pairs, slices_keep)


        # Save compact loaded summaries for download/checking
        summary_dir = out_dir / "summary_tables"
        summary_dir.mkdir(parents=True, exist_ok=True)
        for key, df in results.items():
            df.to_parquet(summary_dir / f"df_{key}.parquet", index=False)

        # Direction-label verification table.
        direction_audit = pd.concat([
            audit_following_direction(df_obs_events, id_pair=id_pair, bin_labels=bin_labels, name="observed"),
            audit_following_direction(df_sim_events, id_pair=id_pair, bin_labels=bin_labels, name="simulated"),
        ], ignore_index=True)
        direction_audit.to_csv(summary_dir / f"{label}_{raw_pair}_following_direction_audit.csv", index=False)

        # Determine slices from interactions. Use HR slices later as fallback.
        slices_from_events = sorted([
            int(x) for x in pd.concat([
                df_sim_events["slice"].dropna(),
                df_obs_events["slice"].dropna()
            ], ignore_index=True).unique()
        ]) if (not df_sim_events.empty or not df_obs_events.empty) else []

        # ---------------------------------------------------------
        # Figure 1: null model three-panel
        # ---------------------------------------------------------
        fig1_status = "not_run"
        if not df_sim_events.empty:
            slices_for_fig1 = slices_from_events
            if len(slices_for_fig1) == 0:
                slices_for_fig1 = sorted([int(x) for x in df_sim_events["slice"].dropna().unique()])

            plot_slicewise_threepanel(
                df_sim_events=df_sim_events,
                df_obs_events=df_obs_events,
                id_pair=id_pair,
                bin_labels=bin_labels,
                concurrent_bin="0-1h",
                slices=slices_for_fig1,
                bins=20,
                figsize_per_row=(7, 4),
                title_fs=16,
                label_fs=14,
                tick_fs=12,
                star_fs=30,
                legend_fs=14,
                save_path=fig1_path,
                show=False,
            )
            copy_to_collection(fig1_path, collect_dir)
            fig1_status = "saved"
        else:
            # Still write a marker so we know why no Fig 1 was created
            (out_dir / f"{label}_{raw_pair}_Fig1_NOT_CREATED.txt").write_text(
                "No simulated interaction events were found; null-model three-panel figure was not created.\n"
            )
            fig1_status = "no_sim_events"

        # ---------------------------------------------------------
        # Figure 2/3 data preparation for Figure 4
        # ---------------------------------------------------------
        gdf_slices, point_slice = compute_slice_home_ranges_with_points(
            file_path=str(TRACKING_FILE),
            id_pairs=[id_pair],
            adjusted_dir=str(ADJUSTED_DIR),
            window_hours=WINDOW_HOURS,
        )

        if gdf_slices.empty:
            raise ValueError(f"No home-range slices generated for {raw_pair}")

        # Keep all partitions that exist in the HR table
        valid_hr_slices = sorted([int(x) for x in gdf_slices["slice"].dropna().unique()])

        gdf_merged = integrate_event_counts(
            df_obs_events=df_obs_events,
            gdf_slices=gdf_slices,
            time_bins=bin_labels,
            id_pair=id_pair,
        )

        gdf_slices_plot  = filter_slices(gdf_slices, slices_keep)
        point_slice_plot = filter_slices(point_slice, slices_keep)

        gdf_enriched = attach_ppa_to_gdf(
            gdf_merged=gdf_merged,
            df_obs_pairs=df_obs_pairs,
            bin_labels=bin_labels,
            time_bins=time_bins,
            id_pair=id_pair,
            df_obs_events=df_obs_events,
        )

        gdf_idx = compute_indices(
            gdf_enriched,
            area_col="overlapped_area_km2",
            prop_col="ppa_prop",
            opportunity_col="all_ppa",
            group_by_pair=True,
        )
        gdf_idx = standardize_metric_table_for_plot(gdf_idx)

        gdf_idx_plot = filter_slices(gdf_idx, slices_keep)
        if "time_bin" in gdf_idx_plot.columns:
            gdf_idx_plot["time_bin"] = pd.Categorical(
                gdf_idx_plot["time_bin"],
                categories=bin_labels,
                ordered=True
            )

        # Circle-metric verification table. If metric_missing is True, the circle
        # would be blank/transparent in the plot.
        circle_metric_audit = audit_circle_metrics(
            gdf_idx=gdf_idx,
            id_pair=id_pair,
            bin_labels=bin_labels,
            expected_slices=valid_hr_slices,
        )
        circle_metric_audit.to_csv(summary_dir / f"{label}_{raw_pair}_circle_metric_audit.csv", index=False)
        n_bad_metric = int(circle_metric_audit["metric_missing"].sum()) if not circle_metric_audit.empty else 0
        if n_bad_metric > 0:
            print(f"[WARNING] {label} ({raw_pair}) has {n_bad_metric} missing circle metric rows. See circle_metric_audit.csv")

        # Save Figure 4 data tables
        _safe_to_csv(gdf_slices, summary_dir / f"{label}_{raw_pair}_home_range_slices.csv")
        _safe_to_csv(point_slice, summary_dir / f"{label}_{raw_pair}_tracking_points_by_slice.csv")
        _safe_to_csv(gdf_idx, summary_dir / f"{label}_{raw_pair}_interaction_index_table.csv")
        gdf_idx.to_parquet(summary_dir / f"{label}_{raw_pair}_interaction_index_table.parquet", index=False)

        # ---------------------------------------------------------
        # Figure 4: home range + circle heatmap grid
        # ---------------------------------------------------------
        # plot_slices_hr_kde_grid_split(
        #     boundary_gdf=gdf_slices_plot,
        #     point_gdf=point_slice_plot,
        #     gdf_idx=gdf_idx_plot,
        #     id_pair=id_pair,
        #     bin_labels=bin_labels,
        #     circle_size_range=(20, 300),
        #     circle_band_height=0.2,
        #     save_path=fig4_path,
        #     show=False,
        # )

        plot_slices_hr_kde_grid_split(
            boundary_gdf=gdf_slices,
            point_gdf=point_slice,
            gdf_idx=gdf_idx,
            id_pair=id_pair,
            bin_labels=bin_labels,
            circle_size_range=(20, 300),
            circle_band_height=0.2,
            save_path=fig4_path,
            show=False,
        )
        copy_to_collection(fig4_path, collect_dir)

        # Metadata
        meta = {
            "pair": raw_pair,
            "label": label,
            "analysis_name": analysis_name,
            "pair_dir": str(pdir),
            "output_dir": str(out_dir),
            "collection_dir": str(collect_dir),
            "fig1_status": fig1_status,
            "fig1_path": str(fig1_path),
            "fig4_path": str(fig4_path),
            "n_sim_events": int(len(df_sim_events)),
            "n_sim_pairs": int(len(df_sim_pairs)),
            "n_obs_events": int(len(df_obs_events)),
            "n_obs_pairs": int(len(df_obs_pairs)),
            "hr_slices": valid_hr_slices,
            "event_slices": slices_from_events,
            "n_missing_circle_metric_rows": n_bad_metric,
        }
        with open(out_dir / f"{label}_{raw_pair}_visualization_metadata.json", "w") as f:
            json.dump(meta, f, indent=2, default=str)

        return {
            "pair": raw_pair,
            "label": label,
            "status": "ok",
            "fig1_status": fig1_status,
            "fig1": str(fig1_path),
            "fig4": str(fig4_path),
            "output_dir": str(out_dir),
        }

    except Exception as e:
        err_path = out_dir / f"{label}_{raw_pair}_visualization_FAILED.txt"
        err_path.write_text(repr(e))
        return {
            "pair": raw_pair,
            "label": label,
            "status": "failed",
            "error": repr(e),
            "output_dir": str(out_dir),
        }

In [ ]:
# =============================================================================
# Run supplementary visualization for all completed dyads
# =============================================================================

# Pairs repaired from old interaction folders.
# These may appear as NEEDS_LOG_OR_DONE_CHECK in status table,
# but we trust them because the interaction parquet files now cover MC 1-1000.
REPAIRED_FULL_MC_PAIRS = [
    (131343, 37821),
    (131343, 37823),
    (229032, 37821),
]

# Pair-specific partition limits for main-text style figures
# MAX_PARTITION_BY_PAIR = {
#     (131343, 37823): 4,   # FT1-ML4: only show first 4 partitions
# }

# Set to None to use all pairs marked ALL_VALID_DONE in run_status_pair_level_v3.csv.
# Or set manually, e.g. ID_PAIRS_TO_PLOT = [(229011, 31898)]
ID_PAIRS_TO_PLOT = None 

# If True, only pairs marked ALL_VALID_DONE in run_status_pair_level_v3.csv are plotted.
ONLY_COMPLETED_FROM_STATUS = False

# If True, overwrite existing figure outputs.
FORCE_REMAKE_FIGURES = True #False

status_df = load_status_table()

if ID_PAIRS_TO_PLOT is None:
    id_pairs_to_plot = []
    
    if ONLY_COMPLETED_FROM_STATUS:
        id_pairs_to_plot.extend(
            completed_pairs_from_status(
                status_df,
                analysis_name=MAIN_ANALYSIS_NAME
            )
        )
    else:
        id_pairs_to_plot.extend(ALL_MAIN_ID_PAIRS)

    # Add repaired old pairs manually
    id_pairs_to_plot.extend(REPAIRED_FULL_MC_PAIRS)

else:
    id_pairs_to_plot = [tuple(x) for x in ID_PAIRS_TO_PLOT]

# Remove duplicates while preserving order
seen = set()
id_pairs_to_plot_unique = []
for p in id_pairs_to_plot:
    p = tuple(p)
    if p not in seen:
        seen.add(p)
        id_pairs_to_plot_unique.append(p)

id_pairs_to_plot = id_pairs_to_plot_unique
    
# Keep only folders that actually exist
id_pairs_to_plot = [p for p in id_pairs_to_plot if pair_dir_hpc(p).exists()]

print(f"Pairs selected for visualization: {len(id_pairs_to_plot)}")
print([f"{pair_label(p)} ({pair_id_string(p)})" for p in id_pairs_to_plot])

# Save selection list
pd.DataFrame({
    "pair": [pair_id_string(p) for p in id_pairs_to_plot],
    "label": [pair_label(p) for p in id_pairs_to_plot],
    "pair_dir": [str(pair_dir_hpc(p)) for p in id_pairs_to_plot],
}).to_csv(SUPP_FIG_ROOT / "pairs_selected_for_supplementary_visualization.csv", index=False)

#### Parellel processing

In [ ]:
# Parallel generation.
# If multiprocessing gives trouble in Jupyter, set N_WORKERS_FOR_FIGS = 1 and rerun this cell.

N_WORKERS_FOR_FIGS = 3 #min(N_WORKERS, max(1, len(id_pairs_to_plot)))
print("N_WORKERS_FOR_FIGS =", N_WORKERS_FOR_FIGS)

results = []

if N_WORKERS_FOR_FIGS == 1:
    for p in tqdm(id_pairs_to_plot, desc="Generating supplementary figures"):
        results.append(make_visualizations_for_pair_hpc(
            p,
            analysis_name=MAIN_ANALYSIS_NAME,
            max_mc=MAX_MC_FOR_FIGURES,
            force=FORCE_REMAKE_FIGURES,
            verbose=False,
            # max_partition=MAX_PARTITION_BY_PAIR.get(tuple(p), None),
        ))
else:
    # Use fork on Linux HPC so notebook-defined functions are available in workers.
    mp_ctx = mp.get_context("fork")
    with ProcessPoolExecutor(max_workers=N_WORKERS_FOR_FIGS, mp_context=mp_ctx) as exe:
        futures = {
            exe.submit(
                make_visualizations_for_pair_hpc,
                p,
                MAIN_ANALYSIS_NAME,
                MAX_MC_FOR_FIGURES,
                FORCE_REMAKE_FIGURES,
                False,
                # MAX_PARTITION_BY_PAIR.get(tuple(p), None),
            ): p
            for p in id_pairs_to_plot
        }

        for fut in tqdm(as_completed(futures), total=len(futures), desc="Generating supplementary figures"):
            results.append(fut.result())

results_df = pd.DataFrame(results)
status_path = SUPP_FIG_ROOT / "supplementary_figure_generation_status.csv"
results_df.to_csv(status_path, index=False)

print("Saved:", status_path)
display(results_df)

In [ ]:
# Parallel generation.
# If multiprocessing gives trouble in Jupyter, set N_WORKERS_FOR_FIGS = 1 and rerun this cell.

N_WORKERS_FOR_FIGS = 1 #min(N_WORKERS, max(1, len(id_pairs_to_plot)))
print("N_WORKERS_FOR_FIGS =", N_WORKERS_FOR_FIGS)

results = []

if N_WORKERS_FOR_FIGS == 1:
    for p in tqdm(id_pairs_to_plot, desc="Generating supplementary figures"):
        results.append(make_visualizations_for_pair_hpc(
            p,
            analysis_name=MAIN_ANALYSIS_NAME,
            max_mc=MAX_MC_FOR_FIGURES,
            force=FORCE_REMAKE_FIGURES,
            verbose=False,
            max_partition=MAX_PARTITION_BY_PAIR.get(tuple(p), None),
        ))
else:
    # Use fork on Linux HPC so notebook-defined functions are available in workers.
    mp_ctx = mp.get_context("fork")
    with ProcessPoolExecutor(max_workers=N_WORKERS_FOR_FIGS, mp_context=mp_ctx) as exe:
        futures = {
            exe.submit(
                make_visualizations_for_pair_hpc,
                p,
                MAIN_ANALYSIS_NAME,
                MAX_MC_FOR_FIGURES,
                FORCE_REMAKE_FIGURES,
                False,
                MAX_PARTITION_BY_PAIR.get(tuple(p), None),
            ): p
            for p in id_pairs_to_plot
        }

        for fut in tqdm(as_completed(futures), total=len(futures), desc="Generating supplementary figures"):
            results.append(fut.result())

results_df = pd.DataFrame(results)
status_path = SUPP_FIG_ROOT / "supplementary_figure_generation_status_f4p.csv"
results_df.to_csv(status_path, index=False)

print("Saved:", status_path)
display(results_df)

In [ ]:
# Quick check: list generated figure files
fig_files = sorted(SUPP_FIG_ROOT.rglob("*.png"))
print(f"Generated PNG files: {len(fig_files)}")
for fp in fig_files[:20]:
    print(fp)
if len(fig_files) > 20:
    print("...")

## Figure 5: Overall Description

In [70]:
summary_data = [
    ["MT3-ML2","High-conflict dynamics", "Leopard-following","Tiger-following","Tiger-following","Bidirectional following",None,None,None,None,None,None,None,None],
    ["FT1-FL","Home range shift competition", "No overlap","Leopard-following","No overlap","No overlap","No overlap","No overlap","No overlap","No overlap",None,None,None,None],
    ["FT1-ML2","Home range shift competition", "Leopard-following","Tiger-following","Avoidance","Avoidance",None,None,None,None,None,None,None,None],
    ["FT1-ML3","Home range shift competition", "Leopard-following","Avoidance","No overlap",None,None,None,None,None,None,None,None,None],
    ["MT2-ML3","Home range shift competition", "Leopard-following","Avoidance",None,None,None,None,None,None,None,None,None,None],
    ["FT3-FL","Home range shift competition", "Avoidance","No overlap","No overlap","Tiger-following",None,None,None,None,None,None,None,None],
    ["MT3-ML3","Home range shift competition", "Avoidance","Avoidance","No overlap",None,None,None,None,None,None,None,None,None],
    ["MT3-ML1","Home range shift competition", "Avoidance","Avoidance","Avoidance",None,None,None,None,None,None,None,None,None],
    ["FT2-ML1","Home range shift competition", "Avoidance","Avoidance",None,None,None,None,None,None,None,None,None,None],
    ["MT2-FL","Home range shift competition", "Avoidance","Avoidance",None,None,None,None,None,None,None,None,None,None],
    ["MT2-ML1","Home range shift competition", "Avoidance","Avoidance",None,None,None,None,None,None,None,None,None,None],
    ["FT1-ML1","Stable coexistence", "Leopard-following","Tiger-following","Tiger-following","Avoidance","Avoidance","Leopard-following","Avoidance","Avoidance","Avoidance","Avoidance","Leopard-following","Tiger-following"],
    ["FT1-ML4","Stable coexistence", "Leopard-following","Leopard-following","Tiger-following","Leopard-following","Tiger-following","Tiger-following","Avoidance","Avoidance","Avoidance",None,None,None],
    ["FT3-ML1","Stable coexistence", "Avoidance","Tiger-following","Avoidance","Avoidance","Avoidance","Avoidance","Leopard-following","Tiger-following",None,None,None,None],
    ["MT1-ML4","Stable coexistence", "Avoidance","Tiger-following","Tiger-following","Tiger-following","Leopard-following","Avoidance","Avoidance","Tiger-following",None,None,None,None],
    ["MT2-ML4","Stable coexistence", "Avoidance","Tiger-following","Leopard-following","Leopard-following","Leopard-following","Tiger-following","Leopard-following","Tiger-following","Tiger-following",None,None,None],
    ["MT3-ML4","Stable coexistence", "Leopard-following","Leopard-following","Leopard-following","Tiger-following","Tiger-following","Leopard-following","Leopard-following","Avoidance",None,None,None,None],
]

cols = ["Pair","Type"] + [f"Slice {i}" for i in range(12)]
df_summary = pd.DataFrame(summary_data, columns=cols)

df_summary.head()

,Pair,Type,Slice 0,Slice 1,Slice 2,Slice 3,Slice 4,Slice 5,Slice 6,Slice 7,Slice 8,Slice 9,Slice 10,Slice 11
0,MT3-ML2,High-conflict dynamics,Leopard-following,Tiger-following,Tiger-following,Bidirectional following,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FT1-FL,Home range shift competition,No overlap,Leopard-following,No overlap,No overlap,No overlap,No overlap,No overlap,No overlap,NaN,NaN,NaN,NaN
2,FT1-ML2,Home range shift competition,Leopard-following,Tiger-following,Avoidance,Avoidance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FT1-ML3,Home range shift competition,Leopard-following,Avoidance,No overlap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MT2-ML3,Home range shift competition,Leopard-following,Avoidance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Simple classification

In [71]:
def row_to_features(row):
    vals = [row[c] for c in slice_cols]
    vals = [v for v in vals if v is not None and not (isinstance(v, float) and np.isnan(v))]
    n = len(vals) if len(vals)>0 else 1
    feats = {f"prop_{lab}": vals.count(lab)/n for lab in labels}
    feats["n_slices_nonnull"] = n
    # Balance & dominance metrics
    feats["follow_balance"] = feats["prop_Tiger-following"] - feats["prop_Leopard-following"]
    feats["avoidance_dominance"] = feats["prop_Avoidance"] - max(feats["prop_Tiger-following"], feats["prop_Leopard-following"])
    feats["any_chasing"] = 1.0 if ("Bidirectional following" in vals) else 0.0
    return feats

In [72]:
# --- Feature engineering: proportions of slice-level labels by pair ---
slice_cols = [c for c in df_summary.columns if c.startswith("Slice")]
labels = ["Leopard-following","Tiger-following","Avoidance","No overlap","Bidirectional following"]

X = df_summary.apply(row_to_features, axis=1, result_type="expand")
X["Pair"] = df_summary["Pair"]
y = df_summary["Type"]

In [73]:
# Show the engineered feature table (rounded for readability)
display_cols = ["Pair"] + [c for c in X.columns if c!="Pair"]
X_display = X.copy()
for c in display_cols:
    if c!="Pair":
        X_display[c] = X_display[c].astype(float).round(3)

X_display

,prop_Leopard-following,prop_Tiger-following,prop_Avoidance,prop_No overlap,prop_Bidirectional following,n_slices_nonnull,follow_balance,avoidance_dominance,any_chasing,Pair
0,0.250,0.500,0.000,0.000,0.25,4.0,0.250,-0.500,1.0,MT3-ML2
1,0.125,0.000,0.000,0.875,0.00,8.0,-0.125,-0.125,0.0,FT1-FL
2,0.250,0.250,0.500,0.000,0.00,4.0,0.000,0.250,0.0,FT1-ML2
3,0.333,0.000,0.333,0.333,0.00,3.0,-0.333,0.000,0.0,FT1-ML3
4,0.500,0.000,0.500,0.000,0.00,2.0,-0.500,0.000,0.0,MT2-ML3
5,0.000,0.250,0.250,0.500,0.00,4.0,0.250,0.000,0.0,FT3-FL
6,0.000,0.000,0.667,0.333,0.00,3.0,0.000,0.667,0.0,MT3-ML3
7,0.000,0.000,1.000,0.000,0.00,3.0,0.000,1.000,0.0,MT3-ML1
8,0.000,0.000,1.000,0.000,0.00,2.0,0.000,1.000,0.0,FT2-ML1
9,0.000,0.000,1.000,0.000,0.00,2.0,0.000,1.000,0.0,MT2-FL
10,0.000,0.000,1.000,0.000,0.00,2.0,0.000,1.000,0.0,MT2-ML1
11,0.250,0.250,0.500,0.000,0.00,12.0,0.000,0.250,0.0,FT1-ML1
12,0.333,0.333,0.333,0.000,0.00,9.0,0.000,0.000,0.0,FT1-ML4
13,0.125,0.250,0.625,0.000,0.00,8.0,0.125,0.375,0.0,FT3-ML1
14,0.125,0.500,0.375,0.000,0.00,8.0,0.375,-0.125,0.0,MT1-ML4
15,0.444,0.444,0.111,0.000,0.00,9.0,0.000,-0.333,0.0,MT2-ML4
16,0.625,0.250,0.125,0.000,0.00,8.0,-0.375,-0.500,0.0,MT3-ML4

In [40]:
# --- A very small, simple classifier ---
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import LeaveOneOut, cross_val_predict
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.multiclass import OneVsRestClassifier

pipe = Pipeline([
    ("scaler", StandardScaler(with_mean=True, with_std=True)),
    ("clf", OneVsRestClassifier(LogisticRegression(max_iter=1000)))
])

loo = LeaveOneOut()
# Convert Arrow/pandas-backed arrays to normal numpy arrays for sklearn
X_mat = (
    X.drop(columns=["Pair"])
     .apply(pd.to_numeric, errors="coerce")
     .fillna(0)
     .to_numpy(dtype=float)
)

y_vec = (
    pd.Series(y)
      .astype("string")
      .astype(str)
      .to_numpy(dtype=object)
)

# Base KDD predictions (LOOCV)
y_pred = cross_val_predict(pipe, X_mat, y_vec, cv=loo)

print("=== Base KDD (no rule) ===")
print(classification_report(y_vec, y_pred, zero_division=0))
print("Accuracy:", accuracy_score(y_vec, y_pred))
print("Labels:", sorted(pd.Series(y_vec).unique()))
print(confusion_matrix(y_vec, y_pred, labels=sorted(pd.Series(y_vec).unique())))

=== Base KDD (no rule) ===
                              precision    recall  f1-score   support

      High-conflict dynamics       0.00      0.00      0.00         1
Home range shift competition       1.00      1.00      1.00        10
          Stable coexistence       0.86      1.00      0.92         6

                    accuracy                           0.94        17
                   macro avg       0.62      0.67      0.64        17
                weighted avg       0.89      0.94      0.91        17

Accuracy: 0.9411764705882353
Labels: ['High-conflict dynamics', 'Home range shift competition', 'Stable coexistence']
[[ 0  0  1]
 [ 0 10  0]
 [ 0  0  6]]

In [41]:
# --- Rule override: if any_chasing == 1.0 → High-conflict dynamics ---
y_pred_rule = y_pred.copy()
any_chasing_mask = (X["any_chasing"].values == 1.0)
y_pred_rule[any_chasing_mask] = "High-conflict dynamics"

print("\n=== KDD + Rule (chasing ⇒ High-conflict) ===")
print(classification_report(y_vec, y_pred_rule, zero_division=0))
print("Accuracy:", accuracy_score(y_vec, y_pred_rule))
print("Labels:", sorted(pd.Series(y_vec).unique()))
print(confusion_matrix(y_vec, y_pred_rule, labels=sorted(pd.Series(y_vec).unique())))

=== KDD + Rule (chasing ⇒ High-conflict) ===
                              precision    recall  f1-score   support

      High-conflict dynamics       1.00      1.00      1.00         1
Home range shift competition       1.00      1.00      1.00        10
          Stable coexistence       1.00      1.00      1.00         6

                    accuracy                           1.00        17
                   macro avg       1.00      1.00      1.00        17
                weighted avg       1.00      1.00      1.00        17

Accuracy: 1.0
Labels: ['High-conflict dynamics', 'Home range shift competition', 'Stable coexistence']
[[ 1  0  0]
 [ 0 10  0]
 [ 0  0  6]]

In [42]:
# --- Comparison table: Visual vs KDD vs KDD+Rule ---
df_compare = pd.DataFrame({
    "Pair": X["Pair"],
    "Visual_Label": y_vec,
    "KDD_Label": y_pred,
    "KDD_Label_WithRule": y_pred_rule
})
print("\n=== Comparison (first few rows) ===")
df_compare.head(20)

=== Comparison (first few rows) ===

,Pair,Visual_Label,KDD_Label,KDD_Label_WithRule
0,MT3-ML2,High-conflict dynamics,Stable coexistence,High-conflict dynamics
1,FT1-FL,Home range shift competition,Home range shift competition,Home range shift competition
2,FT1-ML2,Home range shift competition,Home range shift competition,Home range shift competition
3,FT1-ML3,Home range shift competition,Home range shift competition,Home range shift competition
4,MT2-ML3,Home range shift competition,Home range shift competition,Home range shift competition
5,FT3-FL,Home range shift competition,Home range shift competition,Home range shift competition
6,MT3-ML3,Home range shift competition,Home range shift competition,Home range shift competition
7,MT3-ML1,Home range shift competition,Home range shift competition,Home range shift competition
8,FT2-ML1,Home range shift competition,Home range shift competition,Home range shift competition
9,MT2-FL,Home range shift competition,Home range shift competition,Home range shift competition
10,MT2-ML1,Home range shift competition,Home range shift competition,Home range shift competition
11,FT1-ML1,Stable coexistence,Stable coexistence,Stable coexistence
12,FT1-ML4,Stable coexistence,Stable coexistence,Stable coexistence
13,FT3-ML1,Stable coexistence,Stable coexistence,Stable coexistence
14,MT1-ML4,Stable coexistence,Stable coexistence,Stable coexistence
15,MT2-ML4,Stable coexistence,Stable coexistence,Stable coexistence
16,MT3-ML4,Stable coexistence,Stable coexistence,Stable coexistence

In [74]:
# ============================================================
# Feature importance table from standardized logistic regression
# ============================================================

from sklearn.base import clone

feature_names = X.drop(columns=["Pair"]).columns.tolist()

# Fit the same base classifier on all 17 dyads
pipe_full = clone(pipe)
pipe_full.fit(X_mat, y_vec)

ovr_clf = pipe_full.named_steps["clf"]
class_labels = ovr_clf.classes_

coef_rows = []

for class_label, estimator in zip(class_labels, ovr_clf.estimators_):
    coefs = estimator.coef_[0]

    for feat, coef in zip(feature_names, coefs):
        coef_rows.append({
            "class": class_label,
            "feature": feat,
            "standardized_coefficient": coef,
            "absolute_coefficient": abs(coef)
        })

coef_table = pd.DataFrame(coef_rows)

# Class-specific coefficient table
coef_wide = (
    coef_table
    .pivot(index="feature", columns="class", values="standardized_coefficient")
    .reset_index()
)

# Overall importance = mean absolute standardized coefficient across one-vs-rest classifiers
feature_importance = (
    coef_table
    .groupby("feature", as_index=False)
    .agg(
        mean_abs_standardized_coefficient=("absolute_coefficient", "mean"),
        max_abs_standardized_coefficient=("absolute_coefficient", "max")
    )
    .sort_values("mean_abs_standardized_coefficient", ascending=False)
)

display(coef_wide)
display(feature_importance)

class,feature,High-conflict dynamics,Home range shift competition,Stable coexistence
0,any_chasing,0.623436,-0.188046,-0.371591
1,avoidance_dominance,-0.176733,0.348005,-0.260443
2,follow_balance,0.164446,-0.295167,0.217178
3,n_slices_nonnull,-0.107996,-1.197360,1.306040
4,prop_Avoidance,-0.181965,0.169018,-0.067448
5,prop_Bidirectional following,0.623436,-0.188046,-0.371591
6,prop_Leopard-following,0.018104,-0.376129,0.385814
7,prop_No overlap,-0.071360,0.670914,-0.623428
8,prop_Tiger-following,0.210703,-0.735817,0.654905

,feature,mean_abs_standardized_coefficient,max_abs_standardized_coefficient
3,n_slices_nonnull,0.870465,1.306040
8,prop_Tiger-following,0.533808,0.735817
7,prop_No overlap,0.455234,0.670914
5,prop_Bidirectional following,0.394358,0.623436
0,any_chasing,0.394358,0.623436
1,avoidance_dominance,0.261727,0.348005
6,prop_Leopard-following,0.260015,0.385814
2,follow_balance,0.225597,0.295167
4,prop_Avoidance,0.139477,0.181965

In [75]:
OUT_DIR = Path("OUT_DIR")
OUT_DIR.mkdir(parents=True, exist_ok=True)

X_display.to_csv(OUT_DIR / "pair_level_engineered_features.csv", index=False)
df_compare.to_csv(OUT_DIR / "pair_level_classification_predictions.csv", index=False)
coef_wide.to_csv(OUT_DIR / "pair_level_classifier_standardized_coefficients.csv", index=False)
feature_importance.to_csv(OUT_DIR / "pair_level_classifier_feature_importance.csv", index=False)

In [76]:
labels_order = [
    "High-conflict dynamics",
    "Home range shift competition",
    "Stable coexistence"
]

cm_base = pd.DataFrame(
    confusion_matrix(y_vec, y_pred, labels=labels_order),
    index=[f"Observed: {x}" for x in labels_order],
    columns=[f"Predicted: {x}" for x in labels_order]
)

cm_rule = pd.DataFrame(
    confusion_matrix(y_vec, y_pred_rule, labels=labels_order),
    index=[f"Observed: {x}" for x in labels_order],
    columns=[f"Predicted: {x}" for x in labels_order]
)

display(cm_base)
display(cm_rule)

cm_base.to_csv(OUT_DIR / "pair_level_base_classifier_confusion_matrix.csv")
cm_rule.to_csv(OUT_DIR / "pair_level_classifier_plus_rule_confusion_matrix.csv")

,Predicted: High-conflict dynamics,Predicted: Home range shift competition,Predicted: Stable coexistence
Observed: High-conflict dynamics,0,0,1
Observed: Home range shift competition,0,10,0
Observed: Stable coexistence,0,0,6

,Predicted: High-conflict dynamics,Predicted: Home range shift competition,Predicted: Stable coexistence
Observed: High-conflict dynamics,1,0,0
Observed: Home range shift competition,0,10,0
Observed: Stable coexistence,0,0,6

### Figure

In [43]:
# Define mapping of interaction patterns to colors
pattern_styles = {
    "Tiger-following": {"color": "#f6a582", "hatch": "///"},      # red, diagonal forward
    "Leopard-following": {"color": "#8ec3de", "hatch": "\\\\\\"},      # blue, diagonal backward
    "Bidirectional following": {"color": "#c3a4cf", "hatch": "xxx"},   # purple, cross
    "Avoidance": {"color": "#add4a0", "hatch": "..."} ,            # green, dots
    "No overlap": {"color": "#ECF3F6", "hatch": "ooo"},            # grey, circles
    None: {"color": "#FFFFFF", "hatch": ""}                        # white for empty cells, no hatch
}

# Convert to a matrix of colors
pairs = df_summary["Pair"].tolist()
slices = [col for col in df_summary.columns if col.startswith("Slice")]
# Convert to a matrix of colors, treating NaN/None as blank
DEFAULT_STYLE = pattern_styles.get(None, "#FFFFFF")  # white if None is defined; otherwise white

color_matrix = np.array([
    [
        pattern_styles.get(df_summary.loc[i, sl], DEFAULT_STYLE)
        if pd.notna(df_summary.loc[i, sl])
        else DEFAULT_STYLE
        for sl in slices
    ]
    for i in range(len(df_summary))
])

In [ ]:
from matplotlib.patches import Patch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

# Make sure missing slices have a blank style
blank_style = {"color": "white", "hatch": ""}

# Optional: add None style if not already included
pattern_styles[None] = blank_style

# Output folder on HPC
FIG_DIR = Path("PROJECT_PATH") / "simulated_trajectory" / "supplementary_figures_all_dyads"
FIG_DIR.mkdir(parents=True, exist_ok=True)

# Plot with textures
fig, ax = plt.subplots(figsize=(12, 8))

for i in range(len(pairs)):
    for j in range(len(slices)):
        pattern = df_summary.loc[i, slices[j]]

        # Handle NaN/None safely
        if pd.isna(pattern):
            style = blank_style
        else:
            style = pattern_styles.get(pattern, blank_style)

        rect = plt.Rectangle(
            (j, i), 1, 1,
            facecolor=style["color"],
            hatch=style["hatch"],
            edgecolor="k",
            linewidth=0.2
        )
        ax.add_patch(rect)

# Set axis ticks and labels
ax.set_xticks(np.arange(len(slices)) + 0.5)
ax.set_xticklabels([str(int(s.replace("Slice ", "")) + 1) for s in slices])

ax.set_yticks(np.arange(len(pairs)) + 0.5)
ax.set_yticklabels(pairs)

ax.set_xlim(0, len(slices))
ax.set_ylim(0, len(pairs))
ax.invert_yaxis()

# Create legend with hatches; exclude None / missing / blank
legend_elements = [
    Patch(
        facecolor=style["color"],
        hatch=style["hatch"],
        edgecolor="k",
        label=pattern
    )
    for pattern, style in pattern_styles.items()
    if pattern is not None and not pd.isna(pattern)
]

ax.legend(
    handles=legend_elements,
    loc="lower right",
    title="Interaction State"
)

ax.set_xlabel("Partition", fontsize=14)
ax.set_ylabel("Pair", fontsize=14)

# --- Add category labels ---
ax.text(
    len(slices) + 0.2, 0.5,
    "High-conflict \n dynamics",
    va="center", ha="left",
    fontsize=12, fontweight="bold"
)

ax.text(
    len(slices) + 0.2, (2 + 10 - 1) / 2 + 0.5,
    "Home range shift \n competition",
    va="center", ha="left",
    fontsize=12, fontweight="bold"
)

ax.text(
    len(slices) + 0.2, (12 + len(pairs) - 1) / 2 + 0.5,
    "Stable Coexistence",
    va="center", ha="left",
    fontsize=12, fontweight="bold"
)

# --- Add dividing lines ---
ax.hlines(1, 0, len(slices), colors="black", linewidth=2)
ax.hlines(11, 0, len(slices), colors="black", linewidth=2)

plt.tight_layout()

out_path = FIG_DIR / "Overall_description.jpg"
plt.savefig(out_path, dpi=500, bbox_inches="tight")
plt.show()

print("Saved to:", out_path)